# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : fuzzel
version    : 1.14.1
release    : 4
source     :
    - https://codeberg.org/dnkl/fuzzel/releases/download/1.14.1/fuzzel-1.14.1.tar.gz : a3af48d00d5cb7cb5526ab86bd632c62dbea5901693fdd746a2e7bb5bd64cf04
homepage   : https://codeberg.org/dnkl/fuzzel
license    : MIT
component  : desktop
summary    : App launcher and fuzzy finder for Wayland, inspired by rofi and dmenu
description: |
    Fuzzel is a Wayland-native application launcher and fuzzy finder, inspired by rofi and dmenu.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(fcft)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xkbcommon)
    - scdoc
setup      : |
    %meson_configure \
        --sysconfdir=/usr/share \
        -Denable-cairo=enabled \
        -Dsvg-backend=librsvg
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
