name       : pdfsam
version    : 5.2.2
release    : 9
source     :
    - https://github.com/torakiki/pdfsam/archive/refs/tags/v5.2.2.tar.gz : 4eec571fe9a385ee1977e6ef4671e6dec86183216b4ab48718ed1fbfb282fd44
homepage   : https://pdfsam.org/
license    : AGPL-3.0-only
component  : office
summary    : PDFsam Basic, a free, open source, multi-platform software designed to split, merge, extract pages, mix and rotate PDF files.
description: |
    PDFsam Basic, a free, open source, multi-platform software designed to split, merge, extract pages, mix and rotate PDF files.
builddeps  :
    - apache-maven
    - openjdk-21
    - gnupg  # doesn't fix compile error "failed to execute gpg"
    # try `ls -l $(which gpg)` and `chmod +x $(which gpg)` if needed
rundeps    :
    - openjdk-21
networking : yes
environment: |
    export JAVA_HOME=/usr/lib64/openjdk-21
    export PATH=$JAVA_HOME/bin:$PATH
setup      : |
    %apply_patches
#     #   https://java-online-training.de/?page_id=83
#     # https://stackoverflow.com/questions/63835578/maven-javadoc-enable-preview
#     # <compilerArgs>
#     #  <arg>--enable-preview</arg>
#     # </compilerArgs>
#     #
#     # <additionalOptions>--enable-preview</additionalOptions>
build      : |
    cat pom.xml
    export MAVEN_OPTS="-Dmaven.repo.local=./m2"
    mvn -DskipTests -Drelease -Dgpg.skip package
    # mvn clean package -DskipTests -Drelease
    
install    : |
    # export MAVEN_OPTS="-Dmaven.repo.local=./m2"
    # mvn clean install -DskipTests -Drelease
    install -Dm00644 pdfsam-basic/target/assembled/pdfsam-basic-$version.jar $installdir/usr/share/pdfsam/pdfsam.jar
    install -dm00755 $installdir/usr/share/pdfsam/lib/
    install -Dm00644 pdfsam-basic/target/assembled/lib/* $installdir/usr/share/pdfsam/lib/
    install -Dm00644 pdfsam-basic/src/deb/icon.svg $installdir/usr/share/icons/hicolor/scalable/apps/pdfsam.svg
    install -Dm00755 $pkgfiles/pdfsam.sh $installdir/usr/bin/pdfsam
    install -Dm00644 $pkgfiles/pdfsam.desktop -t $installdir/usr/share/applications
