# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : crun
version    : '1.27'
release    : 3
source     :
    - https://github.com/containers/crun/releases/download/1.27/crun-1.27.tar.zst : bfe10f9201f71191b9339f56560b60f097cffb6b4d2a4d68da8e2e5b3ab16017
homepage   : https://github.com/containers/crun
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
component  : virt
libsplit   : false
summary    : A fast and low-memory footprint OCI Container Runtime fully written in C.
description: |
    - A fast and lightweight fully featured OCI runtime and C library for running containers
builddeps  :
    - pkgconfig(libcap-ng)
    - pkgconfig(libseccomp)
    - pkgconfig(libsystemd)
    - pkgconfig(yajl)
    - go-md2man
    - gperf
setup      : |
    %configure --enable-shared --disable-static
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING*
