# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : iniparser
version    : 4.2.6
release    : 3
source     :
    - https://gitlab.com/iniparser/iniparser/-/archive/v4.2.6/iniparser-v4.2.6.tar.gz : 67575ed032a544d5359610e5f697af786371bbc3eb01311218ef8adfd3e5e329
homepage   : https://iniparser.gitlab.io/iniparser/
license    : MIT
component  : programming.library
summary    : ini file parser
description: |
    iniParser is a simple C library offering ini file parsing services. The library is pretty small (less than 1500 lines of C) and robust, and does not depend on any other external library to compile. It is written in C and should compile on most platforms without difficulty.
setup      : |
    %cmake_ninja \
        -DBUILD_STATIC_LIBS=OFF \
        -DBUILD_DOCS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
