# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : nghttp2
version    : 1.68.1
release    : 19
source     :
    - https://github.com/nghttp2/nghttp2/releases/download/v1.68.1/nghttp2-1.68.1.tar.xz : 6abd7ab0a7f1580d5914457cb3c85eb80455657ee5119206edbd7f848c14f0b2
license    : MIT
component  : system.base
emul32     : true
homepage   : https://nghttp2.org/
summary    : HTTP/2 C Library
description: |
    This is an implementation of the Hypertext Transfer Protocol version 2 in C.
builddeps  :
    - pkgconfig32(openssl)
setup      : |
    %cmake_ninja \
                 -DENABLE_LIB_ONLY=ON \
                 -DCMAKE_INSTALL_LIBDIR=%libdir%
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING

    rm -rf $installdir/usr/share/doc \
           $installdir/usr/share/man
