# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : opus
version    : 1.6.1
release    : 13
source     :
    - https://downloads.xiph.org/releases/opus/opus-1.6.1.tar.gz : 6ffcb593207be92584df15b32466ed64bbec99109f007c82205f0194572411a1
license    : BSD-3-Clause
component  : multimedia.codecs
homepage   : https://www.opus-codec.org/
summary    : Opus is a totally open, royalty-free, highly versatile audio codec.
description: |
    Opus is a totally open, royalty-free, highly versatile audio codec. Opus is unmatched for interactive speech and music transmission over the Internet, but is also intended for storage and streaming applications. It is standardized by the Internet Engineering Task Force (IETF) as RFC 6716 which incorporated technology from Skype’s SILK codec and Xiph.Org’s CELT codec.
libsplit   : false
emul32     : true
setup      : |
    %meson_configure -Dcustom-modes=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
check      : |
    %ninja_check
