# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : ent
version    : 0.1.0
release    : 4
source     :
    # Commit date 2026-04-21
    - git|https://github.com/aerynOS/ent.git : 99637f03b9e273a07af9c21e14455f7eb8377538
homepage   : https://github.com/aerynOS/ent
license    : MPL-2.0
component  : programming.tools
summary    : Tree management
description: |
    ent is a tool for working with packaging recipes in git trees/monorepos. Primarily it is intended for use with Serpent OS packaging, and to a limited degree, Solus packaging.
networking : true
builddeps:
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build --no-default-features --features "ypkg"
install    : |
    %cargo_install
    %install_license LICENSE
