# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : inotify-tools
version    : 4.25.9.0
release    : 6
source     :
    - https://github.com/inotify-tools/inotify-tools/archive/refs/tags/4.25.9.0.tar.gz : d33a4fd24c72c2d08893f129d724adf725b93dae96c359e4f4e9f32573cc853b
homepage   : https://github.com/rvoicilas/inotify-tools/wiki
license    : GPL-2.0-or-later
component  : system.base
summary    : inotify-tools is a C library and a set of command-line programs for Linux providing a simple interface to inotify.
description: |
    inotify-tools is a set of command-line programs for Linux providing a simple  interface to inotify. These programs can be used to monitor and act upon filesystem events. inotify-tools consists of two utilities:

    inotifywait simply blocks for inotify events, making it appropriate for use in shell scripts.

    inotifywatch collects filesystem usage statistics and outputs counts of each inotify event.

setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
