# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : keyd
version    : 2.6.0
release    : 6
source     :
    - https://github.com/rvaiya/keyd/archive/refs/tags/v2.6.0.tar.gz : 697089681915b89d9e98caf93d870dbd4abce768af8a647d54650a6a90744e26
homepage   : https://github.com/rvaiya/keyd
license    : MIT
component  : system.utils
summary    : A key remapping daemon for linux.
description: |
    keyd provides a flexible system wide daemon which remaps keys using kernel level input primitives (evdev, uinput).
build      : |
    %make
install    : |
    %make_install \
        PREFIX=/usr \
        FORCE_SYSTEMD=1 \
        SOCKET_PATH=/run/keyd.socket
    %install_license LICENSE

    install -Dm00644 -t ${installdir}/%libdir%/tmpfiles.d/ ${pkgfiles}/keyd.conf
    install -Dm00644 -t ${installdir}/%libdir%/systemd/system-preset/ ${pkgfiles}/60-keyd.preset

    rm -vrf ${installdir}/etc
