# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : stunnel
version    : '5.78'
release    : 21
source     :
    - https://www.stunnel.org/downloads/stunnel-5.78.tar.gz : fada662282c73923ff1c39ae7089c487694ecea92098a0e3190a81a6f492d3a0
homepage   : https://www.stunnel.org/
license    : GPL-2.0-or-later
component  : network.util
summary    : TLS offloading and load-balancing proxy
description: |
    The stunnel program is designed to work as TLS encryption wrapper between remote clients and local (inetd-startable) or remote servers. The concept is that having non-TLS aware daemons running on your system you can easily set them up to communicate with clients over secure TLS channels.
checkdeps  :
    - nmap
    - python-cryptography
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -D -m00644 $installdir/usr/share/doc/stunnel/examples/stunnel.service -t $installdir/%libdir%/systemd/system
    %install_license COPYING.md COPYRIGHT.md

    rm $installdir/usr/share/doc/stunnel/INSTALL*
    rm $installdir/usr/share/doc/stunnel/examples/stunnel.{rh.init,spec}
check      : |
    %make check
