# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : pulseaudio
version    : '17.0'
release    : 65
source     :
    - https://freedesktop.org/software/pulseaudio/releases/pulseaudio-17.0.tar.xz : 053794d6671a3e397d849e478a80b82a63cb9d8ca296bd35b73317bb5ceb87b5
homepage   : https://www.freedesktop.org/wiki/Software/PulseAudio/
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MIT
component  :
    - multimedia.audio
    - utils : multimedia.audio
summary    :
    - PulseAudio client libraries
    - utils : Utilities for PulseAudio
description: |
    This package only provides the client libraries for PulseAudio. The daemon itself is provided by PipeWire.
emul32     : true
ccache     : false
optimize   : size
builddeps  :
    - pkgconfig32(gtk+-3.0)
    - pkgconfig32(libsystemd)
    - pkgconfig32(sndfile)
    - pkgconfig32(x11-xcb)
rundeps    :
    - rtkit
    - utils :
        - pulseaudio
setup      : |
    %patch -p1 -i ${pkgfiles}/0001-Support-a-stateless-configuration.patch

    %meson_configure \
        -Dclient=true \
        -Ddaemon=false \
        -Ddoxygen=false \
        -Dglib=enabled \
        -Dgsettings=enabled \
        -Dgstreamer=disabled \
        -Dman=true \
        -Dsystemd=enabled \
        -Dtests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE GPL LGPL src/pulsecore/filter/LICENSE.WEBKIT

    # Not useful
    rm -rvf ${installdir}/usr/bin/pa-info
patterns   :
    - utils :
        - /usr/bin/pa*
        - /usr/share/bash-completion/
        - /usr/share/locale/
        - /usr/share/man/man1/
        - /usr/share/zsh/site-functions/
