# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : perl-image-exiftool
version    : '13.50'
release    : 25
source     :
    - https://github.com/exiftool/exiftool/archive/refs/tags/13.50.tar.gz : f392ec4f5471d0bc5d4de20ab23efe61392eb6e09e780781b9407e2eb95ad31e
homepage   : https://exiftool.org/
license    : GPL-3.0-or-later
component  : multimedia.library
summary    : Reader and rewriter of EXIF informations that supports raw files
description: |
    ExifTool is a customizable set of Perl modules plus a full-featured command-line application for reading and writing meta information in a wide variety of files, including the maker note information of many digital cameras by various manufacturers such as Canon, Casio, DJI, FLIR, FujiFilm, GE, GoPro, HP, JVC/Victor, Kodak, Leaf, Minolta/Konica-Minolta, Nikon, Nintendo, Olympus/Epson, Panasonic/Leica, Pentax/Asahi, Phase One, Reconyx, Ricoh, Samsung, Sanyo, Sigma/Foveon and Sony.
builddeps  :
    - perl-archive-zip
    - perl-posix-strptime
rundeps    :
    - perl-archive-zip
    - perl-posix-strptime
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
    %install_license LICENSE
check      : |
    %perl_build test
