# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libva-utils
version    : 2.23.0
release    : 21
source     :
    - https://github.com/intel/libva-utils/archive/refs/tags/2.23.0.tar.gz : fa7ff29847b55010fbbb775b35382f97f29b7b97abe9a2f6fb3e22b36db5440a
license    : MIT
component  : system.utils
homepage   : https://github.com/intel/libva-utils
summary    : Libva-utils is a collection of tests for VA-API (VIdeo Acceleration API).
description: |
    Libva-utils is a collection of tests for VA-API (VIdeo Acceleration API).
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libva)
    - pkgconfig(wayland-client)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
