# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libgoffice
version    : 0.10.60
release    : 32
source     :
    - https://download.gnome.org/sources/goffice/0.10/goffice-0.10.60.tar.xz : 01154338cbffac172fc53338ebb9d527c821ffc21985a2ccfa84923ee6b761c5
homepage   : https://gitlab.gnome.org/GNOME/goffice/
license    :
    - GPL-2.0-only
    - GPL-3.0-only
component  : programming.library
summary    : A GLib/GTK set of document-centric objects and charting library
description: |
    The GOffice package contains a library of GLib/GTK document centric objects and utilities.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgsf-1)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libxslt)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
