# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libspatialindex
version    : 2.1.0
release    : 5
source     :
    - https://github.com/libspatialindex/libspatialindex/releases/download/2.1.0/spatialindex-src-2.1.0.tar.bz2 : c59932395e98896038d59199f2e2453595df6d730ffbe09d69df2a661bcb619b
license    : MIT
component  : programming.library
homepage   : https://libspatialindex.org
summary    : C++ implementation of R*-tree, an MVR-tree and a TPR-tree with C API
description: |
    C++ implementation of R*-tree, an MVR-tree and a TPR-tree with C API.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
check      : |
    %ninja_check
