# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : lzip
version    : '1.26'
release    : 9
source     :
    - https://download.savannah.nongnu.org/releases/lzip/lzip-1.26.tar.gz : 641cf30961525cbe3b340cc883436c8854e9f5032f459f444de4782b621e6572
homepage   : https://www.nongnu.org/lzip/
license    : GPL-2.0-or-later
component  : system.base
summary    : Lossless data compressor
description: |
    Lzip is a lossless data compressor with a user interface similar to the one of gzip or bzip2. Lzip is about as fast as gzip, compresses most files more than bzip2, and is better than both from a data recovery perspective. Lzip is a clean implementation of the LZMA "algorithm".
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
check      : |
    %make check
