# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : jemalloc
version    : 5.3.1
release    : 13
source     :
    - https://github.com/jemalloc/jemalloc/releases/download/5.3.1/jemalloc-5.3.1.tar.bz2 : 3826bc80232f22ed5c4662f3034f799ca316e819103bdc7bb99018a421706f92
homepage   : https://jemalloc.net/
license    : BSD-2-Clause
component  : programming
summary    : jemalloc is a general purpose malloc(3) implementation that emphasizes fragmentation avoidance and scalable concurrency support.
description: |
    jemalloc is a general purpose malloc(3) implementation that emphasizes fragmentation avoidance and scalable concurrency support.
setup      : |
    %configure_no_runstatedir --prefix=/usr --disable-static --disable-fill
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
