# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gnome-user-docs
version    : '50.0'
release    : 39
source     :
    - https://download.gnome.org/sources/gnome-user-docs/50/gnome-user-docs-50.0.tar.xz : e8e23324184c7e985c504f05f6d9c63420c9a9d1f64efde5da2a811236072f78
homepage   : https://gitlab.gnome.org/GNOME/gnome-user-docs
license    : CC-BY-3.0
component  : desktop.gnome.doc
summary    : GNOME core documentation
description: |
    This package contains documents which will be packaged together and shipped as gnome-user-docs in the core GNOME distribution. They should be documents targeted for end-users of GNOME and have general GNOME applicability.
builddeps  :
    - pkgconfig(yelp-xsl)
    - itstool
    - yelp-tools
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
