# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : lftp
version    : 4.9.3
release    : 23
source     :
    - https://lftp.yar.ru/ftp/lftp-4.9.3.tar.xz : 96e7199d7935be33cf6b1161e955b2aab40ab77ecdf2a19cea4fc1193f457edc
homepage   : https://lftp.yar.ru
license    : GPL-3.0-or-later
component  : network.clients
summary    : Terminal based FTP Client
description: |
    LFTP is a sophisticated ftp/http client, and a file transfer program supporting a number of network protocols.
builddeps  :
    - pkgconfig(gnutls)
setup      : |
    %configure_no_runstatedir \
        --disable-static \
        --with-openssl=/usr/bin/openssl
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING

    rm $installdir/%libdir%/*.a
