# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gnome-nibbles
version    : 4.5.1
release    : 22
source     :
    - https://download.gnome.org/sources/gnome-nibbles/4.5/gnome-nibbles-4.5.1.tar.xz : 84bad2825d39b8bf701ef644aab16b2dc7e72bb43e3f8702d23eec9613d29637
homepage   : https://gitlab.gnome.org/GNOME/gnome-nibbles/-/wikis/home
license    : GPL-3.0-or-later
component  : games.arcade
summary    : Guide a worm around a maze
description: |
    Nibbles is a Snake game for GNOME. The aim of the game is to swallow as many objects as you can while avoiding maze walls and other worms. You have to complete 26 levels to finish the game.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gsound)
    - pkgconfig(libadwaita-1)
    - desktop-file-utils
    - itstool
    - vala
    - yelp-tools
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
