# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gnome-clocks
version    : '50.0'
release    : 25
source     :
    - https://download.gnome.org/sources/gnome-clocks/50/gnome-clocks-50.0.tar.xz : bf167f7f44f4f2fb424d4716652c9ba1f29e16e49071e26a1bb833f8dce794c6
homepage   : https://apps.gnome.org/Clocks/
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Keep track of time
description: |
    A simple and elegant clock application. It includes world clocks, alarms, a stopwatch, and timers.
optimize   :
    - lto
builddeps  :
    - pkgconfig(gnome-desktop-4)
    - pkgconfig(gweather4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libgeoclue-2.0)
    - desktop-file-utils
    - itstool
    - vala
    - vorbis-tools
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
