# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : glow
version    : 2.1.2
release    : 7
source     :
    - https://github.com/charmbracelet/glow/archive/refs/tags/v2.1.2.tar.gz : 1b933139da1d08647bf5b3f112cab9548fdc2b40c056c7fa3d84d8706de5265a
homepage   : https://github.com/charmbracelet/glow
license    : MIT
component  : office.notes
summary    : Glow is a terminal based markdown reader designed from the ground up to bring out the beauty—and power—of the CLI.
description: |
    Glow is a terminal based markdown reader designed from the ground up to bring out the beauty—and power—of the CLI. Use it to discover markdown files, read documentation directly on the command line. Glow will find local markdown files in subdirectories or a local Git repository.
networking : true
builddeps  :
    - golang
build      : |
    export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw"
    go build -v -ldflags "-linkmode=external -X main.Version=%version" -o glow .

    # Shell Completions
    ./glow completion bash > glow.bash
    ./glow completion fish > glow.fish
    ./glow completion zsh > _glow
install    : |
    %install_license LICENSE
    install -Dm00755 glow $installdir/usr/bin/glow

    # Install Shell Completions
    install -Dm00644 glow.bash $installdir/usr/share/bash-completion/completions/glow
    install -Dm00644 glow.fish $installdir/usr/share/vendor_completions.d/glow.fish
    install -Dm00644 _glow $installdir/usr/share/zsh/site-functions/_glow
