# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : raqm
version    : 0.10.4
release    : 3
source     :
    - https://github.com/HOST-Oman/libraqm/archive/refs/tags/v0.10.4.tar.gz : 6b583fb0eb159a3727a1e8c653bb0294173a14af8eb60195a775879de72320a3
license    : MIT
homepage   : https://host-oman.github.io/libraqm/
component  : multimedia.library
summary    : A library for complex text layout
description: |
    Raqm is a small library that encapsulates the logic for complex text layout.
    It currently provides bidirectional text support (using FriBiDi), shaping (using HarfBuzz), and proper script itemization. As a result, Raqm can support most writing systems covered by Unicode.
emul32     : true
builddeps  :
    - pkgconfig32(freetype2)
    - pkgconfig32(fribidi)
    - pkgconfig32(harfbuzz)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
check      : |
    %ninja_check
