# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : cantarell-fonts
version    : '0.311'
release    : 14
source     :
    - https://gitlab.gnome.org/GNOME/cantarell-fonts/-/package_files/1276/download : 706778e6f9468d534d7afe05e4f6e1586110395ef37d24df259746736fd6b702
homepage   : https://cantarell.gnome.org/
license    : OFL-1.1
component  : desktop.font
summary    : GNOME Cantarell fonts
description: |
    GNOME Cantarell fonts - required for GNOME 3
builddeps  :
    - intltool
setup      : |
    %meson_configure \
                     -Dbuildappstream=true \
                     -Dfontsdir=/usr/share/fonts/opentype/cantarell/ \
                     -Duseprebuilt=true
build      : |
    %ninja_build
install    : |
    %ninja_install
