# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : xdg-desktop-portal-gnome
version    : '50.0'
release    : 16
source     :
    - https://download.gnome.org/sources/xdg-desktop-portal-gnome/50/xdg-desktop-portal-gnome-50.0.tar.xz : ceeef2fb68b34b3f66a3def0a332a22a70af272641fb6c50065b7a2fde3d5759
homepage   : https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome
license    : LGPL-2.1-or-later
component  : desktop.util
summary    : A backend implementation for xdg-desktop-portal for the GNOME desktop environment.
description: |
    A backend implementation for xdg-desktop-portal for the GNOME desktop environment.
builddeps  :
    - pkgconfig(gnome-desktop-4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(xdg-desktop-portal)
    - gnome-keyring
rundeps    :
    - nautilus
    - xdg-desktop-portal-gtk
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
