# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : tevent
version    : 0.17.1
release    : 21
source     :
    - https://www.samba.org/ftp/tevent/tevent-0.17.1.tar.gz : 1be2dea737cde25fe06621f84945e63eb71259e0c43e9f8f5da482dab1a7be92
homepage   : https://tevent.samba.org
license    : LGPL-3.0-or-later
component  : programming
summary    : Tevent is an event system based on the talloc memory management library
description: |
    Tevent is an event system based on the talloc memory management library
builddeps  :
    - pkgconfig(cmocka)
    - pkgconfig(talloc)
setup      : |
    %configure_no_runstatedir \
      --bundled-libraries=NONE \
      --builtin-libraries=replace \
      --disable-rpath-install \
      --disable-python
build      : |
    %make
install    : |
    %make_install
    %install_license LICENSE
# check      : |
# Disable tests until upstream get it together
#    %make check
