# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : erlang
version    : '28.5'
release    : 50
source     :
    - https://github.com/erlang/otp/archive/refs/tags/OTP-28.5.tar.gz : 7d0a43be4ee5c3965509c0c20cf0b28afa0ab9573f0cc49631f2858165335a5a
homepage   : https://www.erlang.org/
license    : Apache-2.0
component  : programming
summary    : Erlang is a programming language used to build massively scalable systems.
description: |
    Erlang is a programming language used to build massively scalable soft real-time systems with requirements on high availability.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(odbc)
    - pkgconfig(x11)
    - perl
    - wxwidgets-devel
setup      : |
    ./otp_build setup
    %configure --disable-static --enable-shared
build      : |
    %make
install    : |
    %make_install

    # Remove static libraries
    find $installdir/usr/lib64 -name "*.a" -delete
