# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : sratom
version    : 0.6.22
release    : 7
source     :
    - https://gitlab.com/lv2/sratom/-/archive/v0.6.22/sratom-v0.6.22.tar.gz : 4a88bde345370584b279895c2cb8f7f8341d2b31b6ca50e128faea02f02d3e76
homepage   : https://gitlab.com/lv2/sratom
license    :
    - 0BSD
    - ISC
component  : programming.library
summary    : A library for serialising LV2 atoms to or from RDF
description: A library for serialising LV2 atoms to or from RDF, particularly the Turtle syntax.
builddeps  :
    - pkgconfig(lv2)
    - pkgconfig(serd-0)
    - pkgconfig(sord-0)
setup      : |
    %meson_configure --libdir=%libdir%
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
