# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libspelling
version    : 0.4.10
release    : 8
source     :
    - https://download.gnome.org/sources/libspelling/0.4/libspelling-0.4.10.tar.xz : 56e3f01a3a18b575beea4c34349f99cdaba316e1f7c271b1231f7bcf5d9af73b
homepage   : https://gitlab.gnome.org/GNOME/libspelling/
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : A spellcheck library for GTK 4
description: |
    A spellcheck library for GTK 4
optimize   :
    - lto
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(gio-2.0)
    - pkgconfig(gtk4)
    - pkgconfig(gtksourceview-5)
    # pkgconfig(sysprof-capture-4)
    - vala
setup      : |
    %meson_configure -Dsysprof=false -Ddocs=false
build      : |
    %ninja_build
install    : |
    %ninja_install
