# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : sord
version    : 0.16.22
release    : 8
source     :
    - https://gitlab.com/drobilla/sord/-/archive/v0.16.22/sord-v0.16.22.tar.bz2 : 748ee305e5cfd5302604aa995e266a7e55c8a2f5c6359f4fb170419ae2cf84da
homepage   : https://gitlab.com/drobilla/sord
license    :
    - 0BSD
    - BSD-3-Clause
    - ISC
component  : programming.library
summary    : Lightweight library for storing RDF data in memory
description: Lightweight library for storing RDF data in memory
builddeps  :
    - pkgconfig(serd-0)
    - pkgconfig(zix-0)
avx2       : true
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %meson_configure --libdir=%libdir%
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
