# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : hunspell-hu
version    : '1.9'
release    : 5
source     :
    - git|https://git.libreoffice.org/dictionaries : 74b6ae2a2df22fd9d6e253f0391ac3a67cb7b3f8
homepage   : https://magyarispell.sourceforge.net/
license    : GPL-2.0-or-later
component  : office.spelling
summary    : Hungarian hunspell dictionaries
description: |
    Hungarian hunspell dictionaries
rundeps    :
    - libhunspell
install    : |
    cd hu_HU
    install -Ddm00755 $installdir/usr/share/hunspell
    install -m00644 hu_HU.dic hu_HU.aff $installdir/usr/share/hunspell
