# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : sed
version    : '4.10'
release    : 16
source     :
    - https://mirror.kumi.systems/gnu/sed/sed-4.10.tar.xz : b8e72182b2ec96a3574e2998c47b7aaa64cc20ce000d8e9ac313cc07cecf28c7
homepage   : https://www.gnu.org/software/sed/
license    : GPL-3.0-or-later
component  : system.base
summary    : sed (Stream Editor)
description: |
    sed is a stream editor that is meant for manipulating, parsing, and transfoming text.
setup      : |
    %patch -p1 -i $pkgfiles/0001-testsuite-disable-panic-tests.sh.patch
    
    # Fix timestamps to prevent automake from triggering
    touch aclocal.m4
    touch configure
    touch Makefile.in

    %configure
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
check      : |
    %make check
