# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : w3m
version    : 0.5.6
release    : 13
source     :
    - https://git.sr.ht/~rkta/w3m/archive/v0.5.6.tar.gz : 8dd652cd3f31817d68c7263c34eeffb50118c80be19e1159bf8cbf763037095e
homepage   : https://github.com/tats/w3m
license    : MIT
component  : network.web.browser
summary    : w3m is a pager with WWW capability
description: |
    w3m is a pager with WWW capability
builddeps  :
    - pkgconfig(bdw-gc)
    - pkgconfig(harfbuzz)
    - pkgconfig(imlib2)
    - pkgconfig(xext)
setup      : |
    %configure --libexecdir=/usr/lib64 \
               --enable-image=x11,fb \
               --sysconfdir=/etc \
               --with-imagelib=imlib2 \
               --with-termlib=ncurses \
               --disable-w3mmailer
build      : |
    %make -j1
install    : |
    %make_install
    install -Dm 00644 doc/keymap.default $installdir/etc/w3m/keymap
    install -Dm 00644 doc/menu.default $installdir/etc/w3m/menu
    %install_license COPYING
