# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : time
version    : '1.10'
release    : 6
source     :
    - https://ftpmirror.gnu.org/gnu/time/time-1.10.tar.gz : e8c29fb4ab599d8478e41e8618f50db8aede9c90af27d0d2ef28ae50d5de09c3
homepage   : https://www.gnu.org/software/time
license    : GPL-3.0
component  : system.base
summary    : time (Measure CPU/Memory resource other programs use)
description: |
    time is used with other programs to measure the system resources they use.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
check      : |
    %make check
