# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : hyprwayland-scanner
version    : 0.4.6
release    : 6
source     :
    - https://github.com/hyprwm/hyprwayland-scanner/archive/refs/tags/v0.4.6.tar.gz : 05f55fd1a20d8ca81b5030980fdb7c87147749230145bdb3745af2741d617f5c
homepage   : https://github.com/hyprwm/hyprwayland-scanner
license    : BSD-3-Clause
component  : desktop.hyprland
summary    : A Hyprland implementation of wayland-scanner
description: |
    A Hyprland implementation of wayland-scanner, in and for C++.
builddeps  :
    - pkgconfig(pugixml)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
patterns   :
    - /*
