# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : cjson
version    : 1.7.19
release    : 4
source     :
    - https://github.com/DaveGamble/cJSON/archive/refs/tags/v1.7.19.tar.gz : 7fa616e3046edfa7a28a32d5f9eacfd23f92900fe1f8ccd988c1662f30454562
license    : MIT
homepage   : https://github.com/DaveGamble/cJSON/
component  : programming.library
summary    : Ultralightweight JSON parser in ANSI C
description: |
    Ultralightweight JSON parser in ANSI C
clang      : true
setup      : |
    %patch -p1 -i $pkgfiles/disable-Werror-flag.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
check      : |
    %ninja_check
