# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : lzlib
version    : '1.16'
release    : 2
source     :
    - https://download.savannah.nongnu.org/releases/lzip/lzlib/lzlib-1.16.tar.gz : 203228de911780309dad6813e51541d7ea89469784f01cb661edba080ff1b038
homepage   : https://www.nongnu.org/lzip/
license    : BSD-2-Clause
component  : system.utils
summary    : Lzlib is a data compression library used by plzip
description: |
    Lzlib is a data compression library providing in-memory LZMA compression and decompression functions, including integrity checking of the decompressed data. The compressed data format used by the library is the lzip format. Lzlib is written in C.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
