# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : vc
version    : 1.4.5
release    : 7
source     :
    - https://github.com/VcDevel/Vc/archive/refs/tags/1.4.5.tar.gz : eb734ef4827933fcd67d4c74aef54211b841c350a867c681c73003eb6d511a48
homepage   : https://github.com/VcDevel/Vc
license    : BSD-3-Clause
component  : programming
summary    : SIMD Vector Classes for C++
description: |
    SIMD Vector Classes for C++
patterns   :
    - /usr/include/Vc
    - /usr/lib64
setup      : |
    sed -i 's/lib\//lib64\//' $workdir/CMakeLists.txt
    %cmake_ninja .. \
        -DLIB_SUFFIX=%LIBSUFFIX% \
        -DTARGET_ARCHITECTURE=generic
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
    rm $installdir/usr/lib64/libVc.a
