# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : serd
version    : 0.32.8
release    : 8
source     :
    - https://gitlab.com/drobilla/serd/-/archive/v0.32.8/serd-v0.32.8.tar.gz : c0133d878b4b1abf5cb4b2ec4501ebf688edcfefb12a602e3cc26d9e6577a01c
homepage   : https://gitlab.com/drobilla/serd
license    : ISC
component  : programming.library
summary    : Lightweight RDF parsing library
description: |
    Serd is a lightweight C library for RDF syntax which supports reading and writing Turtle and NTriples.
avx2       : true
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %meson_configure --libdir=%libdir%
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
