# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kanshi
version    : 1.9.0
release    : 2
source     :
    - https://gitlab.freedesktop.org/emersion/kanshi/-/releases/v1.9.0/downloads/kanshi-1.9.0.tar.gz : d5dfdaa7fe65d7105fc0ea4b0d7b7bf6a28b4d39c664e31722000bc9afa61108
homepage   : https://gitlab.freedesktop.org/emersion/kanshi
license    : MIT
component  : desktop
summary    : Dynamic display configuration
description: |
    kanshi allows you to define output profiles that are automatically enabled and disabled on hotplug. For instance, this can be used to turn a laptop's internal screen off when docked.

    This is a Wayland equivalent for tools like autorandr. kanshi can be used on Wayland compositors supporting the wlr-output-management protocol.
builddeps  :
    - pkgconfig(scfg)
    - pkgconfig(vali)
    - pkgconfig(wayland-client)
    - scdoc
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
