# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : fuse
version    : 3.18.2
release    : 19
source     :
    - https://github.com/libfuse/libfuse/releases/download/fuse-3.18.2/fuse-3.18.2.tar.gz : f01de85717e20adf5f98aff324acd85dd73d61a5ca3834d573dcf0bd6e54a298
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
component  : system.utils
homepage   : https://github.com/libfuse/libfuse
summary    : File Systems in User Space
description: |
    File Systems in User Space
builddeps  :
    - libiconv-devel
rundeps    :
    - fuse-common
setup      : |
    %patch -p1 -i $pkgfiles/0001-fusermount-Support-a-stateless-configuration.patch
    %meson_configure \
        -Dudevrulesdir=/usr/lib64/udev/rules.d
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE GPL2.txt LGPL2.txt

    install -Dm0644 $pkgfiles/fuse.conf $installdir/usr/share/defaults/fuse/fuse.conf

    rm -rfv $installdir/etc
    rm -rfv $installdir/dev
patterns   :
    - common :
        - /usr/share/defaults/fuse
