# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : cpp-utilities
version    : 5.33.0
release    : 2
source     :
    - https://github.com/Martchus/cpp-utilities/archive/refs/tags/v5.33.0.tar.gz : ae56ddd9a46751a63703b52cc4ea6abf2fff208b55e3434ac14fbd5c9ba00c67
homepage   : https://github.com/Martchus/cpp-utilities
license    : GPL-2.0-or-later
component  : programming.library
summary    : Common C++ classes and routines such as argument parser, IO and conversion utilities
description: |
    Common C++ classes and routines such as argument parser, IO and conversion utilities
builddeps  :
    - pkgconfig(cppunit)
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Install Licence
    %install_license LICENSE
