# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : tecla
version    : '50.0'
release    : 6
source     :
    - https://download.gnome.org/sources/tecla/50/tecla-50.0.tar.xz : 2542acb24850082e0ccf6aa17af9651db71d22f0e233fdbf5ed0cffe2e45bc06
homepage   : https://gitlab.gnome.org/GNOME/tecla
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Keyboard layout viewer
description: |
    Tecla is a keyboard layout viewer
builddeps  :
    - pkgconfig(libadwaita-1)
    - pkgconfig(wayland-egl)
    - pkgconfig(xkbregistry)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
