# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : lazygit
version    : 0.61.1
release    : 55
source     :
    - https://github.com/jesseduffield/lazygit/archive/refs/tags/v0.61.1.tar.gz : 2a550c9b609c5eb0e1c2640e8114ac05b94c671803f77e08a9dcdbd66372e2c4
license    : MIT
homepage   : https://github.com/jesseduffield/lazygit
component  : programming.tools
summary    : A simple terminal UI for git commands, written in Go with the gocui library.
description: |
    A simple terminal UI for git commands, written in Go with the gocui library.
networking : true
builddeps  :
    - golang
build      : |
    go build -ldflags "-X main.version=$version" -o lazygit

install    : |
    install -Dm00755 $workdir/lazygit $installdir/usr/bin/lazygit
    %install_license LICENSE
