# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : fq
version    : 0.17.0
release    : 6
source     :
    - https://github.com/wader/fq/archive/refs/tags/v0.17.0.tar.gz : c5658b2bc635a1d344c64e37d7311157f0fc4b20cc3cfa4d09bdd2f023692d57
homepage   : https://github.com/wader/fq
license    : MIT
component  : programming.tools
summary    : tool, language and decoders for working with binary and text formats
description: |
    jq for binary formats - tool, language and decoders for working with binary and text formats
networking : true
builddeps  :
    - golang
build      : |
    %make
install    : |
    install -Dm00755 fq -t $installdir/usr/bin/
    %install_license LICENSE
