# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : nemo
version    : 6.6.4
release    : 18
source     :
    - https://github.com/linuxmint/nemo/archive/refs/tags/6.6.4.tar.gz : 258807feb2e7bac523707d6b3daf2d9439e7135123cbe795183d5aaa6fd691ed
homepage   : https://github.com/linuxmint/nemo
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.gtk
summary    : File browser for Cinnamon
description: |
    Nemo is the file manager for the Cinnamon desktop environment.
builddeps  :
    - pkgconfig(cinnamon-desktop)
    - pkgconfig(exempi-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libexif)
    - pkgconfig(libgnomekbdui) # This should be pulled in by xapp, but it isn't
    - pkgconfig(libgsf-1)
    - pkgconfig(libselinux)
    - pkgconfig(xapp)
rundeps    :
    - cinnamon-translations
    - gvfs-goa
    - xapp-symbolic-icons
setup      : |
    %patch -p1 -i $pkgfiles/0001-Allow-changing-the-background-on-Budgie-Desktop.patch

    # Rename 'Files' app name to avoid having the same as nautilus
    sed -i '/^\[Desktop Entry/,/^\[Desktop Action/ s/^Name\(.*\)=.*/Name\1=Nemo/' data/nemo.desktop.in

    %meson_configure -Dselinux=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING COPYING-DOCS COPYING.*
