# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gmmlib
version    : 22.10.0
release    : 25
source     :
    - https://github.com/intel/gmmlib/archive/refs/tags/intel-gmmlib-22.10.0.tar.gz : 893e3c5a24b408ac312a0318b70f38f427f297646e323f31e79d3a06a92c1543
license    : MIT
component  : programming.library
homepage   : https://github.com/intel/gmmlib/
summary    : Intel(R) Graphics Memory Management Library
description: |
    The Intel(R) Graphics Memory Management Library provides device specific and buffer management for the Intel(R) Graphics Compute Runtime for OpenCL(TM) and the Intel(R) Media Driver for VAAPI.
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE.md

    # remove empty dirs in include
    find $installdir/usr/include/igdgmm/GmmLib -type d -empty -delete
