# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : hyphen-fr
version    : 3.0
release    : 2
source     :
    - git|https://anongit.freedesktop.org/git/libreoffice/dictionaries.git : 3fc3d99f071693dd40a78ba1f729ef47dc189692
homepage   : https://wiki.documentfoundation.org/Development/Dictionaries
license    : LGPL-2.0-or-later
component  : office
summary    : French hyphenation rules
description: |
    French hyphenation rules.
rundeps    :
    - hyphen
install    : | 
    install -Dm00644 fr_FR/hyph_fr.dic $installdir/usr/share/hyphen/hyph_fr_FR.dic
    %install_license fr_FR/README_hyph_fr.txt

    pushd $installdir/usr/share/hyphen/
        fr_FR_aliases="fr_BE fr_CA fr_CH fr_LU fr_MC"
        for lang in ${fr_FR_aliases}; do
            ln -s hyph_fr_FR.dic hyph_${lang}.dic
        done
    popd
