name       : webcamoid
version    : 9.4.0
release    : 3
source     :
    - https://github.com/webcamoid/webcamoid/archive/refs/tags/9.4.0.tar.gz : e62fded6650b879f5b3f9ebb48b3c2f198de25bd7accd45d5e2972570cae837c
homepage   : https://webcamoid.github.io
license    : GPL-3.0-or-later
summary    :
    - Webcamoid is a full featured and multiplatform webcam suite.
description:
    - Webcamoid is a full featured and multiplatform webcam suite.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(jack)
    - pkgconfig(libavcodec)
    - pkgconfig(libkmod)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libpulse)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libv4l1)
    - pkgconfig(libvlc)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(Qt6Multimedia)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6UiTools)
    - pkgconfig(sdl3)
    - pkgconfig(x264)
    - gstreamer-plugins-base
    # - libuvc-devel # optional, not in Solus repository
rundeps    :
    - polkit
setup      : |
    %cmake_ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_C_COMPILER=gcc\
        -DCMAKE_CXX_COMPILER=g++
build      : |
    %ninja_build
install    : |
    %ninja_install
