# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : thin-provisioning-tools
version    : 1.3.2
release    : 13
source     :
    - https://github.com/jthornber/thin-provisioning-tools/archive/refs/tags/v1.3.2.tar.gz : 82c4697e7b008567dbc935997f30f2fbaba5450bd4dcab9a820d445a39ac79ce
license    : GPL-3.0-or-later
component  : system.utils
homepage   : https://github.com/jthornber/thin-provisioning-tools
summary    : A suite of tools for manipulating the metadata of the dm-thin, dm-cache and dm-era device-mapper targets
description: |
    A suite of tools for manipulating the metadata of the dm-thin, dm-cache and dm-era device-mapper targets.
networking : true
builddeps  :
    - pkgconfig(devmapper)
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %make_install
