# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : pciutils
version    : 3.15.0
release    : 15
source     :
    - https://mj.ucw.cz/download/linux/pci/pciutils-3.15.0.tar.gz : a42e6e3f76fb6b1f6ac2e08cdd151f6bf78bc4f6312c591f4b6ec197582ede3a
homepage   : https://mj.ucw.cz/sw/pciutils/
license    : GPL-2.0-only
component  : system.utils
emul32     : true
summary    : Utilities to deal with PCI bus
description: |
    The PCI Utilities are a collection of programs for inspecting and manipulating configuration of PCI devices, all based on a common portable library libpci which offers access to the PCI configuration space on a variety of operating systems.
builddeps  :
    - pkgconfig32(libudev)
    - pkgconfig32(zlib)
setup      : |
    # In line with fedora
    %patch -p1 -i $pkgfiles/idpath.patch
build      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        export CC="$CC -m32"
    fi
    %make PREFIX=/usr \
          OPT="$CFLAGS"\
          SHARED=yes \
          MANDIR=/usr/share/man \
          IDSDIR=/usr/share/hwdata \
          PCI_IDS="pci.ids" \
          all \
          CC="$CC"

install    : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        export CC="$CC -m32"
    fi
    %make_install SHARED=yes \
                  PREFIX=/usr \
                  LIBDIR=/%libdir% \
                  INCDIR=/usr/include \
                  MANDIR=/usr/share/man \
                  IDSDIR=/usr/share/hwdata \
                  PCI_IDS="pci.ids" \
                  install-lib \
                  CC="$CC"

    # This is handled by hwdata package
    rm -rfv $installdir/usr/share/hwdata

    %install_license COPYING
