# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : intel-level-zero
version    : 1.28.0
release    : 8
source     :
    - https://github.com/oneapi-src/level-zero/archive/refs/tags/v1.28.0.tar.gz : 92cdffb1e55084857c63672cfe6ef03fd763dec5cca0318d9d02583bf07064a5
license    : MIT
component  : programming.library
homepage   : https://github.com/oneapi-src/level-zero/
summary    : oneAPI Level Zero Specification Headers and Loader
patterns   :
    - /*
description: |
    The oneAPI Level Zero (Level Zero) provides low-level direct-to-metal interfaces that are tailored to the devices in a oneAPI platform. This package includes the Level Zero headers, loader, and validation layer.
builddeps  :
    - opencl-headers
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
