# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : mousepad
version    : 0.7.0
release    : 5
source     :
    - https://archive.xfce.org/src/apps/mousepad/0.7/mousepad-0.7.0.tar.xz : e86c59feb08126d4cace368432c16b2dee8e519aaca8a9d2b409ae1cdd200802
homepage   : https://docs.xfce.org/apps/mousepad/start
license    : GPL-2.0-or-later
component  : desktop.xfce
summary    : Mousepad is a simple text editor for the Xfce desktop environment..
description: |
    Mousepad is a simple text editor for the Xfce desktop environment.
builddeps  :
    - pkgconfig(gspell-1)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(libxfce4ui-2)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
