# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : svtplay-dl
version    : '4.179'
release    : 39
source     :
    - https://github.com/spaam/svtplay-dl/archive/refs/tags/4.179.tar.gz : 7b99d5a528735d0bbb6b7211afad29f60e7fbd39541ab3e305e63ec52a541f4e
homepage   : https://svtplay-dl.se/
license    : MIT
component  : network.download
summary    : Small command-line program to download videos from some streaming sites
description: |
    svtplay-dl is an open source command-line program written in python. You can quickly download published videos from various sites to your local computer.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools
rundeps    :
    - ffmpeg
    - python-cryptography
    - python-pysocks
    - python-requests
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
