# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : grub2
version    : '2.14'
release    : 41
source     :
    - git|https://git.savannah.gnu.org/git/grub.git : d38d6a1a9b79427848976f53d474392cd29c2a71
    - git|https://git.savannah.gnu.org/git/gnulib.git : 9f48fb992a3d7e96610c4ce8be969cff2d61a01b
homepage   : https://www.gnu.org/software/grub/
license    :
    - GPL-3.0-or-later
    # for included terminus fonts in redistributable BDF format
    - OFL-1.1
component  : system.boot
summary    : GRUB Boot Loader
description: |
    GRUB Boot Loader
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(freetype2)
    - pkgconfig(fuse3)
    - pkgconfig(liblz4)
    - pkgconfig(liblzma)
    - autoconf-archive
    - wget
rundeps    :
    - os-prober
networking : true # Needed for bootstrap
strip      : false
environment: |
    unset CFLAGS
    unset CXXFLAGS
    unset LDFLAGS
setup      : |
    cp -a ${sources}/gnulib.git ${workdir}/gnulib

    reverts=(
        # configure: Check linker for --image-base support
        '1a5417f39a0ccefcdd5440f2a67f84d2d2e26960'
        # configure: Print a more helpful error if autoconf-archive is not installed
        'ac042f3f58d33ce9cd5ff61750f06da1a1d7b0eb'
    )

    echo "Applying reverts"
    for _c in "${reverts[@]}"; do
        if [[ "${_c}" == *..* ]]; then _l='--reverse'; else _l='--max-count=1'; fi
        git log --oneline "${_l}" "${_c}"
        git revert --mainline 1 --no-commit "${_c}"
    done

    %apply_patches

    PYTHON=python3 ./bootstrap \
        --gnulib-srcdir="${workdir}/gnulib"

    %autogen \
        --disable-efiemu \
        --disable-werror \
        --enable-device-mapper \
        --enable-grub-mount \
        --target="i386" \
        --with-platform="pc"
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
    install -Dm00755 $pkgfiles/update-grub  -t $installdir/usr/sbin
    install -Dm00755 $pkgfiles/update-grub2 -t $installdir/usr/sbin
    install -Dm00644 $pkgfiles/conf/grub    -t $installdir/etc/default
    install -Dm00644 $pkgfiles/splash.tga   -t $installdir/usr/share/backgrounds
    rm $installdir/etc/grub.d/30_uefi-firmware

    # build grub-compatible PF2 fonts from BDF format terminus fonts in 16x32
    $installdir/usr/bin/grub-mkfont $pkgfiles/font-terminus-bdf/ter-u32b.bdf -o $installdir/usr/share/grub/ter-32b.pf2
    $installdir/usr/bin/grub-mkfont $pkgfiles/font-terminus-bdf/ter-u32n.bdf -o $installdir/usr/share/grub/ter-32n.pf2

    # grub installs /usr/share/grub/unicode.pf2 to /boot/grub/fonts/ by default
    # if grub-install invocations do not specify a --fonts="font1 font2 (...)" argument.
    # Hence, the simplest way to override the default unicode.pf2 font (which is ugly)
    # is to rename it and copy in the font we want to be the default as unicode.pf2
    # This allows users to still use the original font if they so desire.
    install -Dm00644 $pkgfiles/unicode.pf2 $installdir/usr/share/grub/unicode-8x16.pf2
    install -Dm00644 $installdir/usr/share/grub/ter-32b.pf2 $installdir/usr/share/grub/unicode.pf2
