# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libgtkmm-4
version    : 4.22.0
release    : 6
source     :
    - https://download.gnome.org/sources/gtkmm/4.22/gtkmm-4.22.0.tar.xz : 2e8a21b4b0725f620e33aaee0cd343ed121b533275b632896619b1c89e96de67
homepage   : https://gtkmm.org
license    : LGPL-2.1-or-later
component  : desktop.gtk
summary    : C++ bindings to GTK+
description: |
    C++ bindings to GTK+
optimize   :
    - lto
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(gtk4)
    - pkgconfig(pangomm-2.48)
patterns   :
    - devel : [/usr/lib64/g*]
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
