# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : xfce4-settings
version    : 4.20.4
release    : 14
source     :
    - https://archive.xfce.org/src/xfce/xfce4-settings/4.20/xfce4-settings-4.20.4.tar.bz2 : ad5c3c5bfb36f5eb091c05897d60f468d0d5cc4364c8d1d38ca53d8bb04387da
homepage   : https://docs.xfce.org/xfce/xfce4-settings/start
license    : GPL-2.0-or-later
component  : desktop.xfce
summary    : Xfce's Configuration System.
description: |
    Xfce's Configuration System.
builddeps  :
    - pkgconfig(exo-2)
    - pkgconfig(garcon-gtk3-1)
    - pkgconfig(libxfce4ui-2)
    - pkgconfig(libxfconf-0)
    - pkgconfig(libxklavier)
    - pkgconfig(xi)
    - pkgconfig(xrandr)
setup      : |
    %patch -p1 -i $pkgfiles/0001-Use-Solus-defaults.patch

    %configure \
        --enable-xrandr \
        --enable-xcursor \
        --enable-libnotify \
        --enable-libxklavier \
        --enable-pluggable-dialogs \
        --enable-sound-settings \
        --disable-debug \
        --sysconfdir=/usr/share
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
