# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libexif
version    : 0.6.26
release    : 8
source     :
    - https://github.com/libexif/libexif/archive/refs/tags/v0.6.26.tar.gz : 32e591455339504b7d02f3e9b0a48f16f5455462a9059a7f47639980e82e4bc1
homepage   : https://libexif.github.io/
license    : LGPL-2.0-or-later
component  : desktop.library
emul32     : true
summary    : EXIF tag parsing library
description: |
    Most digital cameras produce EXIF files, which are JPEG files with extra tags that contain information about the image. The EXIF library allows you to parse an EXIF file and read the data from those tags.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
