# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gnome-backgrounds
version    : '50.0'
release    : 24
source     :
    - https://download.gnome.org/sources/gnome-backgrounds/50/gnome-backgrounds-50.0.tar.xz : 1acdba7acb4f34c7321febc6273444344fd55fd593611d446de70860183b52b8
homepage   : https://gitlab.gnome.org/GNOME/gnome-backgrounds
license    :
    - CC-BY-SA-3.0
    - GPL-2.0-or-later
component  : desktop.gnome
summary    : Default GNOME artwork
description: |
    Default GNOME artwork
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -m00644 $pkgfiles/*.jpg -t $installdir/usr/share/backgrounds/gnome/
