# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : incus
version    : 6.0.6
release    : 3
source     :
    - https://linuxcontainers.org/downloads/incus/incus-6.0.6.tar.xz : 129a1323605d427c46c8358844f5f9447d7e2cebe0f4ada242c93cf002fb44ea
license    : Apache-2.0
homepage   : https://linuxcontainers.org/incus/
component  : virt
summary    : Daemon based on liblxc offering a REST API to manage containers
description: |
    Incus is a next generation system container and virtual machine manager.
builddeps  :
    - pkgconfig(cowsql)
    - pkgconfig(libacl)
    - pkgconfig(libcap)
    - pkgconfig(libuv)
    - pkgconfig(lxc)
    - pkgconfig(raft)
    - pkgconfig(sqlite3)
    - golang
rundeps    :
    - cdrtools
    - iptables
    - lxcfs
    - qemu
    - rsync
    - squashfs-tools
setup      : |
    # Dynamically replace VarPath with RunPath for LXC hooks
    sed -i '/callhook/s/internalUtil.VarPath/internalUtil.RunPath/g' internal/server/instance/drivers/driver_lxc.go
    
    # Dynamically replace VarDir with RunDir for the daemon UNIX socket
    sed -i 's/s.VarDir, "unix.socket"/s.RunDir, "unix.socket"/g' internal/server/sys/os.go
    mkdir bin
build      : |
    export GOFLAGS="-buildmode=pie -trimpath -modcacherw"
    export CGO_LDFLAGS_ALLOW="-Wl,-z,now"
    GO_LDFLAGS="-compressdwarf=false -linkmode external"

    CGO_LDFLAGS="-static" go build -v -tags "agent" -o bin/ ./cmd/incus-agent/...
    go build -v -ldflags "${GO_LDFLAGS}" -tags "netgo" -o bin/ ./cmd/incus-migrate/...

    for tool in fuidshift incus lxc-to-incus lxd-to-incus incusd incus-benchmark incus-user; do
        go build -v -ldflags "${GO_LDFLAGS}" -tags "libsqlite3" -o bin/ ./cmd/$tool
    done
install    : |
    for tool in incus incusd incus-agent incus-user lxd-to-incus fuidshift lxc-to-incus incus-benchmark; do
        install -v -p -Dm00755 bin/$tool $installdir/usr/bin/$tool
    done

    # Bash completions
    ./bin/incus completion bash | install -Dm644 /dev/stdin "$installdir/usr/share/bash-completion/completions/incus"
    ./bin/incus completion zsh | install -Dm644 /dev/stdin "$installdir/usr/share/zsh/site-functions/_incus"
    ./bin/incus completion fish | install -Dm644 /dev/stdin "$installdir/usr/share/fish/vendor_completions.d/incus.fish"

    install -Dm00644 $pkgfiles/incus.sysusers $installdir/%libdir%/sysusers.d/incus.conf
    install -Dm00644 $pkgfiles/incus.tmpfiles $installdir/%libdir%/tmpfiles.d/incus.conf
    install -Dm00644 $pkgfiles/incus.service $installdir/%libdir%/systemd/system/incus.service
    install -Dm00644 $pkgfiles/incus.socket $installdir/%libdir%/systemd/system/incus.socket
    %install_license COPYING
replaces   :
    - lxd
    - dbginfo :
        - lxd-dbginfo
