# Reference: https://github.com/calamares/calamares/blob/3.2.x-stable/src/modules/partition/partition.conf

---
efi:
  mountPoint: "/boot"
  recommendedSize: 2GiB
  minimumSize: 500MiB
  label: "EFI"

# When a user chooses "Erase"
defaultPartitionTableType:          "gpt"

bootPartitionName:                  "boot"

userSwapChoices:
    - none      # Create no swap, use no swap
    - small     # Up to 4GB
    - suspend   # At least main memory size
    # - reuse     # Re-use existing swap, but don't create any (unsupported right now)
    # - file      # To swap file instead of partition

defaultFileSystemType:              "ext4"

availableFileSystemTypes:           ["ext4","btrfs","f2fs"]

enableLuksAutomatedPartitioning:    true

# This setting specifies the LUKS generation (i.e LUKS1, LUKS2) used internally by
# cryptsetup when creating an encrypted partition.
luksGeneration:                     "luks2"

# Specify whether to create a partition table layout suitable for a hybrid
# (BIOS + EFI) bootloader installation. This has been patched to prepend
# both bios-boot and EFI system partitions to the partition layout only on
# non-EFI systems. Defaults to false.
createHybridBootloaderLayout: true

# LVM support
#
# There is only one sub-key available, *enable* (defaults to true)
# which can be used to show (default) or hide the LVM buttons in the partitioning module.
lvm:
    enable: false
