# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : intel-gpu-tools
version    : '2.4'
release    : 20
homepage   : https://gitlab.freedesktop.org/drm/igt-gpu-tools
source     :
    - https://xorg.freedesktop.org/releases/individual/app/igt-gpu-tools-2.4.tar.xz : a44b7d089a27555944d4cd5da372c9339501539e3cd2735bbdb30e0d802f1cbe
license    : MIT
component  : system.utils
summary    : Tools for development and testing of the Intel DRM driver
description: |
    IGT GPU Tools is a collection of tools for development and testing of the DRM drivers. There are many macro-level test suites that get used against the drivers, including xtest, rendercheck, piglit, and oglconform, but failures from those can be difficult to track down to kernel changes, and many require complicated build procedures or specific testing environments to get useful results. Therefore, IGT GPU Tools includes low-level tools and tests specifically for development and testing of the DRM Drivers.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(cairo)
    - pkgconfig(gsl)
    - pkgconfig(gtk-doc)
    - pkgconfig(jansson) 
    - pkgconfig(libdrm)
    - pkgconfig(libdw)
    - pkgconfig(libkmod)
    - pkgconfig(libpci)
    - pkgconfig(libproc2)
    - pkgconfig(libunwind)
    - pkgconfig(pciaccess)
    - pkgconfig(valgrind)
    - pkgconfig(xmlrpc)
    - pkgconfig(xorg-macros)
    - pkgconfig(xrandr)
    - pkgconfig(xv)
    - curl-devel
    - swig
libsplit   : false
setup      : |
    %meson_configure
build      : |
    %ninja_build
    %ninja_build igt-gpu-tools-doc
install    : |
    %ninja_install
    %install_license COPYING
check      : |
    %ninja_check || :

