# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gocloc
version    : 0.7.0
release    : 2
source     :
    - https://github.com/hhatto/gocloc/archive/refs/tags/v0.7.0.tar.gz : 9375f6699a7bffad42da661b4ba7988af23dd01191da4a4b21eca8f9bb676d9a
homepage   : https://github.com/hhatto/gocloc
license    : MIT
component  : programming.tools
summary    : Go Count Lines Of Code
description: |
    A little fast cloc (Count Lines Of Code), written in Go.
networking : true
builddeps  :
    - golang
build      : |
    %make
install    : |
    install -Dm00755 bin/gocloc $installdir/usr/bin/gocloc
check      : |
    %make test
    %install_license LICENSE
