# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : corrosion
version    : 0.6.1
release    : 5
source     :
    - https://github.com/corrosion-rs/corrosion/archive/refs/tags/v0.6.1.tar.gz : e9e95b1ee2bad52681f347993fb1a5af5cce458c5ce8a2636c9e476e4babf8e3
homepage   : https://github.com/corrosion-rs/corrosion
license    : MIT
component  : programming.tools
summary    : Tools for integrating Rust and CMake
description: |
    Tool for integrating Rust into an existing CMake project
builddeps  :
    - rust
rundeps    :
    - rust
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
patterns   : /*
