# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : mc
version    : 4.8.33
release    : 21
source     :
    - https://github.com/MidnightCommander/mc/archive/refs/tags/4.8.33.tar.gz : 092e440930fda43574739e45a8b41af384b974e6720184b6707d127b84082c51
homepage   : https://midnight-commander.org
license    : GPL-3.0-or-later
component  : system.utils
summary    : GNU midnight commander (ncurses based file manager)
builddeps  :
    - pkgconfig(check)
    - pkgconfig(libssh2)
    - pkgconfig(slang)
    - pkgconfig(x11)
    - gpm-devel
description: |
    GNU Midnight Commander is a visual file manager that allows full file management using the terminal and utilizing ncurses. It allows standard features such as copying, moving, deleting, editing, and searching files.
setup      : |
    # disable helpers tests because they are failing
    sed -i 's| helpers-list||' tests/src/vfs/extfs/Makefile.am

    %patch -p1 -i $pkgfiles/0001-Support-stateless-fallback-of-mc-configuration.patch
    %autogen --disable-static \
        --enable-tests
build      : |
    %make
install    : |
    %make_install -j1
    %install_license COPYING

    # Move config to /usr/share
    install -dm0064 $installdir/usr/share/mc
    cp $installdir/etc/mc/* $installdir/usr/share/mc/
    rm -r $installdir/etc
check      : |
    %make check
