# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : xfce4-terminal
version    : 1.2.0
release    : 8
source     :
    - https://archive.xfce.org/src/apps/xfce4-terminal/1.2/xfce4-terminal-1.2.0.tar.xz : 6874c7b975cc3dc3bd636d57ffec723de7458202defe65377593d3a7e0734b94
homepage   : https://docs.xfce.org/apps/xfce4-terminal/start
license    : GPL-2.0-or-later
component  : desktop.xfce
summary    : Xfce Terminal Emulator.
description: |
    Xfce Terminal Emulator.
builddeps  :
    - pkgconfig(gtk-layer-shell-0)
    - pkgconfig(libxfce4ui-2)
    - pkgconfig(vte-2.91)
    - docbook-xml
setup      : |
    %meson_configure --libexecdir=/usr/lib64/xfce4
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING

    # Install appstream metainfo
    install -Dm00644 $pkgfiles/org.xfce.terminal.metainfo.xml -t $installdir/usr/share/metainfo
