# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : tuxpaint-stamps
version    : 2025.05.26
release    : 4
source     :
    - https://sourceforge.net/projects/tuxpaint/files/tuxpaint-stamps/2025-05-26/tuxpaint-stamps-2025.05.26.tar.gz : 09f4a29f8036c93a64c28134e3afaefb4b9d95a09a71e68fb7537f3c5f82949f
homepage   : https://tuxpaint.org/
license    : GPL-2.0-or-later
component  : games.learning
summary    : Additional stamps for Tux Paint
description: |
    Additional stamps for Tux Paint
rundeps    :
    - tuxpaint
build      : |
    %make
install    : |
    %make DATA_PREFIX=$installdir/usr/share/tuxpaint/ install-all
    %install_license docs/COPYING.txt
