name       : epsonscan2
version    : 6.7.91
release    : 7
source     :
    - https://download-center.epson.com/f/module/b35a1723-196e-44d9-b272-6cfd3e0e6349/epsonscan2-6.7.91.1-1.src.tar.gz : b26e75aa1fe56213891a15e4b9b00d750135c59daad4567aa0233560a3797f09
homepage   : https://support.epson.net/linux/en/epsonscan2.php
license    : GPL-2.1-or-later
component  : office
summary    : Epson Scan 2
description: |
    Software for Epson scanners & multifunction printer
builddeps  :
    - pkgconfig(libusb-1.0)
    - pkgconfig(sane-backends)

    - pkgconfig(zlib)
    - pkgconfig(libtiff-4)
    - pkgconfig(libpng)
    - rapidjson
    - pkgconfig(Qt5Core)
    - libharu-devel
    - libboost-devel
    - libjpeg-turbo-devel
setup      : |
    # Patch CMakeLists
    sed -i 's|/lib/udev|${CMAKE_INSTALL_PREFIX}/lib/udev|' "CMakeLists.txt"
    sed -i '1 i #include "zlib.h"' "src/CommonUtility/DbgLog.cpp"
    sed -i '/zlib/d' "src/Controller/CMakeLists.txt"

    # Stability improvements from Flatpak maintainers (2, 3, 5)
    # https://github.com/flathub/net.epson.epsonscan2
    # Fix a bug when detecting a scanner that does not report its serial number (6, 7)
    # https://github.com/duck7000/aur_epsonscan2/blob/main/0005-Fix-crash-no-serial-number.patch
    %apply_patches

    # Remove Boost setting in CMake config that crashes the package build
    find . -type f -name CMakeLists.txt \
        -exec sed -i '/BOOST_NO_CXX11_RVALUE_REFERENCES/d' {} \;

    for file in Standalone/lastusedsettings.cpp \
                Standalone/defaultsettings.cpp \
                CommonUtility/ESCommonTypedef.h \
                Controller/Src/KeysValues/Key.hpp \
                Controller/Src/KeysValues/KeyMgr.hpp
    do
        sed -i '/BOOST_NO_CXX11_RVALUE_REFERENCES/d' \
            "src/$file"
    done

    # Map arch to solus folder structure
    # $srcdir/$pkgname-$_pkgver/src => src

    # Remove support for older versions of CMake in the configuration scripts
    # (needed to build the package)
    for dir in . \
                src \
                src/Standalone \
                src/ScanSDK \
                src/ScanSDK/Src/SDK/SCANSDKsample_C++ \
                src/DetectAlert
    do
        sed -Ei '/cmake_minimum_required/ s/2\.([0-9]+|\.)+/4.0/' \
                "$dir/CMakeLists.txt"
    done

    # Fix compilation failure caused by GCC 15
    sed -i '/SET.*FLAGS/ s/")/ -Wno-template-body")/' \
            "src/ES2Command/Linux/CMakeLists.txt"

    # Change directory references from "/usr/libexec" to "/usr/lib" in the source code
    for file in Controller/Src/Scanner/Engine.cpp \
                Controller/Src/Filter/GetOrientation.cpp
    do
        sed -i 's/libexec/lib/' \
            "src/$file"
    done

    %cmake_ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DEPSON_OCR_INSTALL_PATH="/usr/share/epsonscan2-ocr" \
        -DQT_VERSION_MAJOR=5
    # -DCMAKE_POLICY_VERSION_MINIMUM=3.5
build      : |
    %ninja_build
install    : |
    %ninja_install

    install -d $installdir/usr/lib64/sane
    # install -Dm644 "$installdir/usr/lib64/epsonscan2/libsane-epsonscan2.so" \
    #     "$installdir/usr/lib64/sane/libsane-epsonscan2.so"
    cd $installdir/usr/lib64/sane
    ln -s ../epsonscan2/libsane-epsonscan2.so libsane-epsonscan2.so
    ln -s ../epsonscan2/libsane-epsonscan2.so libsane-epsonscan2.so.1
    ln -s ../epsonscan2/libsane-epsonscan2.so libsane-epsonscan2.so.1.0.0
    cd -
    
    # Add desktop file
    install -Dm644 "$workdir/desktop/rpm/i686/epsonscan2.desktop" \
        "$installdir/usr/share/applications/epsonscan2.desktop"

    # Rename doc folder
    mv "$installdir/usr/share/doc/epsonscan2-1.0.0.0-1" "$installdir/usr/share/doc/epsonscan2-${version}-1"
    
    # Add metainfo file
    install -Dm644 "$pkgfiles/net.epson.epsonscan2.metainfo.xml" \
        "$installdir/usr/share/metainfo/net.epson.epsonscan2.metainfo.xml"

    # Remove unwanted files
    rm "$installdir/usr/share/doc/epsonscan2-${version}-1/changelog.Debian"

    %install_license LICENSE
