# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : geos
version    : 3.14.1
release    : 6
source     :
    - https://github.com/libgeos/geos/archive/refs/tags/3.14.1.tar.gz : 512118b3be3ccefbca66b36b0f3e895576d08d6ff330ba1511a31a306abbb477
homepage   : https://trac.osgeo.org/geos
license    : LGPL-2.1-only
component  : programming
summary    : GEOS - Geometry Engine, Open Source
description: |
    GEOS (Geometry Engine - Open Source) is a C++ port of the JTS Topology Suite (JTS). It includes the OpenGIS Simple Features for SQL spatial predicate functions and spatial operators, as well as specific JTS enhanced topology functions.
libsplit   : false
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
check      : |
    %ninja_check
patterns   :
    - devel :
        - /usr/bin/geos-config
