# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : isync
version    : 1.5.1
release    : 7
source     :
    - https://sourceforge.net/projects/isync/files/isync/1.5.1/isync-1.5.1.tar.gz : 28cc90288036aa5b6f5307bfc7178a397799003b96f7fd6e4bd2478265bb22fa
homepage   : https://isync.sourceforge.io
license    : GPL-2.0-or-later
component  : network.mail
summary    : isync is a command line application which synchronizes mailboxes
description: |
    isync is a command line application which synchronizes mailboxes; currently Maildir and IMAP4 mailboxes are supported. New messages, message deletions and flag changes can be propagated both ways. isync is suitable for use in IMAP-disconnected mode.
builddeps  :
    - pkgconfig(libsasl2)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    %install_license LICENSES/*
check      : |
    %make check
