# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libsigc++30
version    : 3.8.0
release    : 6
source     :
    - https://github.com/libsigcplusplus/libsigcplusplus/releases/download/3.8.0/libsigc++-3.8.0.tar.xz : 502a743bb07ed7627dd41bd85ec4b93b4954f06b531adc45818d24a959f54e36
homepage   : https://github.com/libsigcplusplus/libsigcplusplus
license    : LGPL-3.0-or-later
component  : desktop.gnome.core
summary    : The libsigc++30 package implements the libsigc++ 3.x ABI for its typesafe callback system for standard C++.
description: |
    The libsigc++30 package implements the libsigc++ 3.x ABI for its typesafe callback system for standard C++.
patterns   :
    - devel :
        - /usr/lib64/sigc++-3.0/include
setup      : |
    %meson_configure -Dbuild-documentation=false -Dbuild-examples=false
build      : |
    %ninja_build
install    : |
    %ninja_install
