# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libass
version    : 0.17.4
release    : 19
source     :
    - https://github.com/libass/libass/releases/download/0.17.4/libass-0.17.4.tar.xz : 78f1179b838d025e9c26e8fef33f8092f65611444ffa1bfc0cfac6a33511a05a
homepage   : https://github.com/libass/libass/
license    : ISC
component  : multimedia.library
summary    : Portable subtitle renderer
description: |
    Libass is a portable library for SSA/ASS subtitles rendering.
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(fribidi)
    - pkgconfig(harfbuzz)
    - pkgconfig(libunibreak)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
