# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : bubblewrap
version    : 0.11.2
release    : 22
source     :
    - https://github.com/containers/bubblewrap/releases/download/v0.11.2/bubblewrap-0.11.2.tar.xz : 69abc30005d2186baf7737feacd8da35633b93cf5af38838ecff17c5f8e924f6
license    : LGPL-2.0-or-later
component  : security
homepage   : https://github.com/containers/bubblewrap/
summary    : Unprivileged sandboxing tool
description: |
    Unprivileged sandboxing tool
builddeps  :
    - pkgconfig(bash-completion)
    - pkgconfig(libcap)
    - docbook-xml
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license COPYING
check      : |
    %ninja_check
