# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : d-spy
version    : '50.0'
release    : 9
source     :
    - https://download.gnome.org/sources/d-spy/50/d-spy-50.0.tar.xz : 1bddc86d8a2cf67b4f652dc461ccd8353112f088753420037c75f5454deaad10
homepage   : https://apps.gnome.org/Dspy/
license    : GPL-3.0-or-later
component  : system.utils
summary    : A D-Bus explorer for GNOME
description: |
    D-Spy is a simple tool to explore D-Bus connections.
optimize   :
    - lto
builddeps  :
    - pkgconfig(libadwaita-1)
    - pkgconfig(libdex-1)
    - desktop-file-utils
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
