# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : opensta
version    : 26.04.17
release    : 3
source     :
    - git|https://github.com/The-OpenROAD-Project/OpenSTA.git : e71e5d7bf72f28a8e96ba088e33adf60373a80b0
homepage   : https://github.com/The-OpenROAD-Project/OpenSTA
license    : GPL-3.0-or-later
component  : office.scientific
summary    : OpenSTA Parallax Static Timing Analyzer
description: |
    OpenSTA is a gate level static timing verifier. As a stand-alone executable it can be used to verify the timing of a design using standard file formats.
clang      : true
libsplit   : false
builddeps  :
    - pkgconfig(eigen3)
    - pkgconfig(tcl)
    - pkgconfig(zlib)
    - cudd-devel
    - gtest
    - swig
setup      : |
    %cmake_ninja \
        -DBUILD_SHARED_LIBS=ON \
        -DTCL_HEADER="%PREFIX%/include/tcl8.6/tcl.h"
build      : |
    %ninja_build
install    : |
    %ninja_install

    export datadir=$installdir/%PREFIX%/share/opensta
    install -dm00755 $datadir/{tcl,spice,dcalc,graph,liberty,network,parasitics,power,sdc,sdf,search,src,util}
    for tclfile in `ls {tcl,spice,dcalc,graph,liberty,network,parasitics,power,sdc,sdf,search,src,util}/*.{tcl,i,hh,cc}`
    do
        cp $tclfile $datadir/$tclfile
    done

    sed -i "s|#include <Eigen|#include <eigen3/Eigen|g" $datadir/*/*.hh

    %install_license LICENSE
