# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : lsof
version    : 4.99.6
release    : 6
source     :
    - https://github.com/lsof-org/lsof/archive/refs/tags/4.99.6.tar.gz : 2ce65158694e9c44dfc54916f5b843d887763c03128e0a1c77d62ae106537009
homepage   : https://github.com/lsof-org/lsof
license    : BSD-4-Clause-UC
component  : system.utils
summary    : lsof (for LiSt Open Files) displays information about files open to Unix processes
description: |
    lsof (for LiSt Open Files) displays information about files open to Unix processes
builddeps  :
    - pkgconfig(libtirpc)
    - groff
setup      : |
    %patch -p1 -i $pkgfiles/lsof-man-page-section.patch
    
    %reconfigure \
        --prefix=/usr \
        --enable-security \
        --enable-no-sock-security \
        --with-libtirpc
build      : |
    %make
install    : |
    install -Dm00755 lsof $installdir/usr/bin/lsof
    install -Dm00644 Lsof.8 $installdir/usr/share/man/man8/lsof.8
    %install_license COPYING
