# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libblastrampoline
version    : 5.15.0
release    : 2
source     :
    - https://github.com/JuliaLinearAlgebra/libblastrampoline/archive/refs/tags/v5.15.0.tar.gz : 69e0be57ebf037c1997c35edf03565614cd3c6863a695d01348a21bf1f482e74
homepage   : https://github.com/JuliaLinearAlgebra/libblastrampoline
license    : MIT
component  : programming.library
summary    : BLAS and LAPACK function loader
description: |
    Using PLT trampolines to provide a BLAS and LAPACK demuxing library.
libsplit   : false
build      : |
    %make -C src LDFLAGS="-shared $LDFLAGS"
install    : |
    %make_install -C src prefix=$installdir/usr
    %install_license LICENSE.md
