# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : simple-scan
version    : '50.0'
release    : 36
source     :
    - https://download.gnome.org/sources/simple-scan/50/simple-scan-50.0.tar.xz : cc32b561ae227182d31a94466632e311723756e3ac90538c3c7e2a2c9aaa4a09
homepage   : https://apps.gnome.org/SimpleScan/
license    : GPL-3.0-or-later
component  : office
summary    : Make a digital copy of your photos and documents
description: |
    A really easy way to scan both text and images. You can crop out the bad parts of an image and rotate it if it is the wrong way round. You can print your scans, export them to pdf, or save them in a range of image formats. This app uses the SANE framework to support most existing scanners.
builddeps  :
    - pkgconfig(colord)
    - pkgconfig(gusb)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libwebp)
    # pkgconfig(packagekit-glib2) future
    - pkgconfig(sane-backends)
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
