# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : lightsoff
version    : '50.0'
release    : 17
source     :
    - https://download.gnome.org/sources/lightsoff/50/lightsoff-50.0.tar.xz : baa0c17431e85eeede5e649f53162f70b4eb1e7c7a6f16a4ecaa3027b6531578
homepage   : https://gitlab.gnome.org/GNOME/lightsoff/
license    : GPL-2.0-or-later
component  : games.puzzle
summary    : Tile based puzzle game
description: |
    Lights Off is a puzzle game, where the objective is to turn off all of the tiles on the board. Each click toggles the state of the clicked tile and its non-diagonal neighbors.
builddeps  :
    - pkgconfig(libadwaita-1)
    - pkgconfig(librsvg-2.0)
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
