name       : ausweis-app
version    : 2.5.0
release    : 6
source     :
    - https://github.com/Governikus/AusweisApp/archive/refs/tags/2.5.0.tar.gz : f74dd258131df2bf97ea92f18016724bc59577125002140a2b9b41e1447ffb3a
homepage   : https://www.ausweisapp.bund.de
license    : EUPL
component  : office
summary    : The AusweisApp is a software for identifying yourself online with your German ID card, your electronic residence permit or the eID card for EU citizens.
description: |
    The AusweisApp is a software for identifying yourself online with your German ID card, your electronic residence permit or the eID card for EU citizens.
builddeps  :
    - pkgconfig(libpcsclite)
    - pkgconfig(Qt6Linguist)
    - pkgconfig(Qt6Scxml)
    - pkgconfig(Qt6ShaderTools)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6WebSockets)
    - qt6-base-private-devel
    - llhttp-devel  # llhttp not available in Solus packages, use `go-task local`
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |-
    %ninja_install
    %install_license LICENSE.txt
