# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gloox
version    : 1.0.28
release    : 8
source     :
    - https://camaya.net/download/gloox-1.0.28.tar.bz2 : 591bd12c249ede0b50a1ef6b99ac0de8ef9c1ba4fd2e186f97a740215cc5966c
license    : GPL-3.0-or-later
component  : programming.library
homepage   : https://camaya.net/
summary    : Full-featured Jabber/XMPP client library, written in clean ANSI C++
description: |
    gloox is a rock-solid, full-featured Jabber/XMPP client library written in C++. It makes writing spec-compliant clients easy and allows for hassle-free integration of Jabber/XMPP functionality into existing applications.
builddeps  :
    - pkgconfig(gnutls)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
check      : |
    %make check
