# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : tdb
version    : 1.4.14
release    : 27
source     :
    - https://www.samba.org/ftp/tdb/tdb-1.4.14.tar.gz : 144f407d42ed7a0ec1470a40ef17ad41133fe910bce865dd9fe084d49c907526
homepage   : https://tdb.samba.org
license    : LGPL-3.0-or-later
component  :
    - database
    - utils : database
summary    : Transactional database
description: |
    This is a simple database API. It was inspired by the realisation that in Samba we have several ad-hoc bits of code that essentially implement small databases for sharing structures between parts of Samba.
builddeps  :
    - pkgconfig(libtirpc)
patterns   :
    - utils : /usr/bin
setup      : |
    %patch -p1 -i $pkgfiles/Fix-invalid-syntax-in-tdb-header.patch
    %configure_no_runstatedir \
      --bundled-libraries=NONE \
      --builtin-libraries=replace \
      --disable-rpath-install \
      --disable-python
build      : |
    %make
install    : |
    %make_install
    %install_license LICENSE
# check      : |
# Disable tests until upstream get it together
#    %make check
