# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : zenity
version    : 4.2.2
release    : 27
source     :
    - https://download.gnome.org/sources/zenity/4.2/zenity-4.2.2.tar.xz : 019186a996096ef4fc356e21577b5673f5baa3a29ac8e3d608b753371c18018d
homepage   : https://gitlab.gnome.org/GNOME/zenity
license    : LGPL-2.0-or-later
component  : desktop.gnome
summary    : A tool that allows you to display GTK dialog boxes in commandline and shell scripts
description: |
    A tool that allows you to display GTK dialog boxes in commandline and shell scripts.
builddeps  :
    - pkgconfig(libadwaita-1)
    - pkgconfig(libnotify)
    - help2man
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
