# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : thunar
version    : 4.20.8
release    : 18
source     :
    - https://archive.xfce.org/src/xfce/thunar/4.20/thunar-4.20.8.tar.bz2 : cc735954d948a88eba2e40016a94c598f876309b736686c9f4d0273a05870c69
homepage   : https://docs.xfce.org/xfce/thunar/start
license    : GPL-2.0-or-later
component  : desktop.xfce
summary    : Modern, fast and easy-to-use file manager for Xfce.
description: |
    Modern, fast and easy-to-use file manager for Xfce.
builddeps  :
    - pkgconfig(exo-2)
    - pkgconfig(libxfce4panel-2.0)
    - pkgconfig(libxfce4ui-2)
rundeps    :
    - gvfs
setup      : |
    %patch -p1 -i $pkgfiles/620.patch

    %configure \
        --disable-debug \
        --enable-dbus \
        --enable-gio-unix \
        --enable-gudev \
        --enable-notifications \
        --enable-exif \
        --sysconfdir=/usr/share
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING COPYING.*
