# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : fping
version    : '5.5'
release    : 7
source     :
    - https://www.fping.org/dist/fping-5.5.tar.gz : 15c4e32b6c55ff105bafe03e8c91c7ca1b2eda31bf9a7127326bb87887ee18fe
homepage   : https://fping.org/
license    : BSD-3-Clause
component  : network.util
summary    : fping is a program like ping which uses the Internet Control Message Protocol
description: |
    fping is a program to send ICMP echo probes to network hosts, similar to ping, but much better performing when pinging multiple hosts.
setup      : |
    %configure --enable-ipv4 --enable-ipv6
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
