# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : mangohud
version    : 0.8.3
release    : 30
source     :
    - https://github.com/flightlessmango/MangoHud/releases/download/v0.8.3/MangoHud-v0.8.3-Source.tar.xz : e810ac73163468533ddb7c74b681f1de4992a3d785dce294fee9933ec8956b05
license    : MIT
component  : system.utils
homepage   : https://github.com/flightlessmango/MangoHud
summary    : Vulkan overlay layer for monitoring FPS, temperatures, CPU/GPU load and more
description: |
    A modification of the Mesa Vulkan overlay. Including GUI improvements, temperature reporting, and logging capabilities.
emul32     : true
libsplit   : false
patterns   :
    - /*
builddeps  :
    - pkgconfig32(libdrm)
    - pkgconfig32(vulkan)
    - pkgconfig32(wayland-client)
    - pkgconfig32(x11)
    - pkgconfig32(xkbcommon)
    - pkgconfig(glfw3)
    - pkgconfig(spdlog)
    - appstream
    - git
    - glslang-devel
    - mako
    - mesalib-devel
    - vulkan-headers
setup      : |
    pushd subprojects
        patch imgui-*/meson.build $pkgfiles/0001-do-not-install-library.patch
    popd
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        build_mangoapp="false"
        system_spdlog="disabled"
    else
        build_mangoapp="true"
        system_spdlog="enabled"
    fi

    %meson_configure -Dmangoapp=$build_mangoapp \
                     -Dinclude_doc=true \
                     -Dwith_xnvctrl=disabled \
                     -Duse_system_spdlog=$system_spdlog \
                     -Dtests=enabled
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
    install -Dm00644 $workdir/data/MangoHud.conf -t $installdir/usr/share/mangohud
check      : |
    %ninja_check
