# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libuv
version    : 1.52.1
release    : 22
source     :
    - https://github.com/libuv/libuv/archive/refs/tags/v1.52.1.tar.gz : 478baf2599bfbc882c355288c9cb6f92e0e7dda435fa04031fa5b607cf3f414c
homepage   : https://libuv.org
license    : MIT
component  : programming.library
summary    : A multi-platform support library with a focus on asynchronous I/O
description: |
    libuv is a multi-platform support library with a focus on asynchronous I/O. It was primarily developed for use by Node.js, but it's also used by Luvit, Julia, pyuv, and others.
setup      : |
    %cmake_ninja -DBUILD_TESTING:BOOL=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
# Tests appear to no longer work
#check      : |
#    unset LD_PRELOAD
#    %ninja_check
