# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libfprint
version    : 1.94.10
release    : 10
source     :
    - https://gitlab.freedesktop.org/libfprint/libfprint/-/archive/v1.94.10/libfprint-v1.94.10.tar.bz2 : 3c781e7920c9af5313d1a51101aadbd18e6e8edb35df3532850477fd96a0e952
homepage   : https://fprint.freedesktop.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Library for fingerprint readers
description: |
    libfprint is an open source software library designed to make it easy for application developers to add support for consumer fingerprint readers to their software.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk-doc)
    - pkgconfig(gudev-1.0)
    - pkgconfig(gusb)
    - pkgconfig(libcrypto)
    - pkgconfig(pixman-1)
    - python-cairo
    - python-gobject
    - umockdev
setup      : |
    %meson_configure -Ddrivers=all -Dinstalled-tests=false
build      : |
    %ninja_build
install    : |
    %install_license COPYING
    %ninja_install
check      : |
    # work around for buildserver
    %ninja_check ||:
