# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : typos
version    : 1.45.2
release    : 5
source     :
    - https://github.com/crate-ci/typos/archive/refs/tags/v1.45.2.tar.gz : 38e111a6c358b92977eb6592f4f7dc3b01920341c8c852f5eb2f2003126b3b7a
license    :
    - Apache-2.0
    - MIT
component  : programming.tools
homepage   : https://github.com/crate-ci/typos
summary    : Source code spell checker
description: |
    Source code spell checker
builddeps  :
    - rust
checkdeps  :
    - rust-devel # Needs rustfmt
networking : true
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install
    %install_license LICENSE-APACHE
    %install_license LICENSE-MIT
check      : |
    %cargo_test
