# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : iwd
version    : '3.12'
release    : 19
source     :
    - https://mirrors.edge.kernel.org/pub/linux/network/wireless/iwd-3.12.tar.xz : d89a5e45c7180170e19be828f9e944a768c593758094fc57a358d0e7c4cb1a49
homepage   : https://iwd.wiki.kernel.org
license    : LGPL-2.1-or-later
component  : network.base
summary    : iNet Wireless Daemon (replacement for wpa_supplicant)
description: |
    iNet Wireless Daemon (iwd) project aims to provide a comprehensive Wi-Fi connectivity solution for Linux based devices. The core goal of the project is to optimize resource utilization: storage, runtime memory and link-time costs. This is accomplished by not depending on any external libraries and utilizes features provided by the Linux Kernel to the maximum extent possible. The result is a self-contained environment that only depends on the Linux Kernel and the runtime C library.
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(ell)
    - pkgconfig(libedit)
    - pkgconfig(readline)
    - pkgconfig(systemd)
    - python-docutils
clang      : true
setup      : |
    %configure \
        --enable-external-ell \
        --enable-hwsim \
        --enable-ofono \
        --enable-tools \
        --enable-wired
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING

    install -Dm00644 ${pkgfiles}/iwd.tmpfiles ${installdir}/usr/lib/tmpfiles.d/iwd.conf
check      : |
    %make check
