# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libunibreak
version    : '7.0'
release    : 6
source     :
    - https://github.com/adah1972/libunibreak/releases/download/libunibreak_7_0/libunibreak-7.0.tar.gz : 8c9a6e121736cd0d5c890ae3ae96f3f4010a19aa040f1dbded833a62a87717d3
homepage   : https://github.com/adah1972/libunibreak
license    : Zlib
component  : programming.library
summary    : Unibreak Library
description: |
    An implementation of the line breaking and word breaking algorithms as described in Unicode Standard Annex 14 and Unicode Standard Annex 29.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    %install_license LICENCE
