# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : slang
version    : 2.3.3
release    : 9
source     :
    - https://www.jedsoft.org/releases/slang/slang-2.3.3.tar.bz2 : f9145054ae131973c61208ea82486d5dd10e3c5cdad23b7c4a0617743c8f5a18
homepage   : https://www.jedsoft.org/slang
license    : GPL-2.0-or-later
component  : programming.library
summary    : Programmers library allowing interactive applications
description: |
    S-Lang is a multi-platform programmer's library designed to allow a developer to create robust multi-platform software. It provides facilities required by interactive applications such as display/screen management, keyboard input, keymaps, and so on. The most exciting feature of the library is the slang interpreter that may be easily embedded into a program to make it extensible. It may also be used standalone with the slsh interpreter.
builddeps  :
    - pkgconfig(libpng)
setup      : |
    %configure --disable-static
build      : |
    %make -j1
install    : |
    %make_install -j1
    %install_license COPYING
check      : |
    # Disable derpy test module for build server 'dumb' terminal
    sed -i "s|TEST_SCRIPTS = test_slsmg.sl|TEST_SCRIPTS =|" modules/Makefile
    LD_PRELOAD='' %make check
