# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libunistring
version    : 1.4.2
release    : 12
source     :
    - https://ftpmirror.gnu.org/gnu/libunistring/libunistring-1.4.2.tar.xz : 5b46e74377ed7409c5b75e7a96f95377b095623b689d8522620927964a41499c
homepage   : https://www.gnu.org/software/libunistring
license    : LGPL-3.0-or-later
component  : system.base
summary    : Library for manipulating Unicode strings
description: |
    libunistring is a GNU library that provides functions for manipulating Unicdoe strings and for manipulating C strings according to the Unicode standard.
emul32     : true
clang      : true
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING
check      : |
    %make check
patterns   :
    - docs :
        - /usr/share/doc/*
