# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gnome-weather
version    : '50.0'
release    : 32
source     :
    - https://download.gnome.org/sources/gnome-weather/50/gnome-weather-50.0.tar.xz : 57de7578605f91f9ab400551ce7738db7505bc88f42a33c70ce7a70167fdb513
homepage   : https://apps.gnome.org/Weather/
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Show weather conditions and forecast
description: |
    A small application that allows you to monitor the current weather conditions for your city, or anywhere in the world. It provides access to detailed forecasts, up to 7 days, with hourly details for the current and next day, using various internet services. It also optionally integrates with the GNOME Shell, allowing you to see the current conditions of the most recently searched cities by just typing the name in the Activities Overview.
optimize   :
    - lto
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gweather4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libgeoclue-2.0)
    - desktop-file-utils
    - typescript
rundeps    :
    - gjs
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
