# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gnome-2048
version    : '50.1'
release    : 20
source     :
    - https://download.gnome.org/sources/gnome-2048/50/gnome-2048-50.1.tar.xz : 438c04575d8013a58ccde3cac3421655eeba6152f5902e51de5779d50531fd60
homepage   : https://gitlab.gnome.org/GNOME/gnome-2048
license    : GPL-3.0-or-later
component  : games.puzzle
summary    : GNOME 2048 Puzzle Game
description: |
    A 2048 clone for GNOME.
networking : true
builddeps  :
    - pkgconfig(libadwaita-1)
    - desktop-file-utils
    - itstool
    - rust-devel
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
