# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : timewarrior
version    : 1.9.1
release    : 5
source     :
    - https://github.com/GothenburgBitFactory/timewarrior/releases/download/v1.9.1/timew-1.9.1.tar.gz : 7ad34f95c0d61d356df55149f9479f8d9aaec417e5f57f2a1cc76ae2f8a3171b
homepage   : https://timewarrior.net/
license    : MIT
component  : office
summary    : Timewarrior tracks and reports time.
description: |
    Timewarrior is a command line time tracking application, which allows you to record time spent on activities. You may be tracking your time for curiosity, or because your work requires it. At its simplest, you tell it to start and stop tracking time.
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc/timew/{AUTHORS,ChangeLog,INSTALL,LICENSE,NEWS,README.md}
    %install_license LICENSE
