# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gpu-screen-recorder-gtk
version    : '5.7.9'
release    : 3
source     :
    - https://dec05eba.com/snapshot/gpu-screen-recorder-gtk.git.5.7.9.tar.gz : c369f128f1f343cef7b76ee3d80c4f132c0684ee0953ef35cc04fe6023ebf8ff
    - git|https://repo.dec05eba.com/gpu-screen-recorder-appdata : 838df59b92fd2e77172e74d34c8b5ddcd14b2e90
homepage   : https://git.dec05eba.com/gpu-screen-recorder-gtk/about/
license    : GPL-3.0-only
component  : multimedia.video
summary    : GTK frontend for GPU Screen Recorder.
description: |
    Gtk frontend to gpu-screen-recorder, a shadowplay-like screen recorder for Linux. The fastest screen recorder for Linux.
clang      : true
builddeps  :
    - pkgconfig(ayatana-appindicator3-0.1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(x11)
    - desktop-file-utils
rundeps    :
    - gpu-screen-recorder
    - libayatana-appindicator
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE

    pushd ${sources}/gpu-screen-recorder-appdata.git
    install -Dm00644 com.dec05eba.gpu_screen_recorder.appdata.xml ${installdir}/usr/share/metainfo/com.dec05eba.gpu_screen_recorder.appdata.xml
    popd
