# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : xarchiver
version    : 0.5.4.26
release    : 3
source     :
    - https://github.com/ib/xarchiver/archive/refs/tags/0.5.4.26.tar.gz : 58e4fb2c1fb8421573a31cf3b4dfec301076d61f48ac5720df632986c87e9573
homepage   : https://github.com/ib/xarchiver
license    : GPL-2.0-or-later
component  : system.utils
summary    : Xarchiver is a Desktop Environment independent archiver front end
description: |
    Xarchiver is a Desktop Environment independent archiver front end. All common archive formats are supported, deb and RPM packages are handled without their package managers being installed.
builddeps  :
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure --libexecdir=/usr/lib64/xfce4
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING

    install -Dm00644 $pkgfiles/xarchiver.metainfo.xml -t $installdir/usr/share/metainfo

    rm $installdir/usr/share/doc/xarchiver/ChangeLog
