# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : museeks
version    : 0.23.4
release    : 5
source     :
    - https://github.com/martpie/museeks/archive/refs/tags/0.23.4.tar.gz : 7f8ab4e077b13cc28fb430174ecc4140ef8cd9f12ad7f0c5712a4254c8409e5e
homepage   : https://museeks.io/
license    : MIT
component  : multimedia.audio
networking : true
summary    : A simple and clean music player.
description: |
    Museeks aims to be a simple and easy to use music player with a clean UI.
builddeps  :
    - pkgconfig(gdk-3.0)
    - pkgconfig(javascriptcoregtk-4.1)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(webkit2gtk-4.1)
    - nodejs
    - rust
setup      : |
    npm ci --ignore-scripts

    pushd src-tauri
    %cargo_fetch
    popd
build      : |
    npm run tauri -- build --no-bundle --ci
install    : |
    install -Dm00755 src-tauri/target/release/museeks "${installdir}/usr/bin/museeks"

    # App reads this path at runtime (--no-bundle does not create it).
    install -Dm00644 src-tauri/icons/icon.png "${installdir}/usr/lib/Museeks/icons/icon.png"

    install -Dm00644 ${pkgfiles}/museeks.desktop "${installdir}/usr/share/applications/io.museeks.app.desktop"
    install -Dm00644 src-tauri/icons/icon.png "${installdir}/usr/share/icons/hicolor/256x256/apps/io.museeks.app.png"

    install -Dm00644 src-tauri/release/flatpak.metainfo.xml "${installdir}/usr/share/metainfo/io.museeks.app.metainfo.xml"

    %install_license LICENSE
