# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : tor
version    : 0.4.9.6
release    : 46
source     :
    - https://dist.torproject.org/tor-0.4.9.6.tar.gz : a89aba97052e9963a654b40df2d46be07e8a6b6e24e5437917fd81acd90a7017
homepage   : https://www.torproject.org/
license    : BSD-3-Clause
component  : security
summary    : Tor is free software and an open network that helps you defend against traffic analysis
description: |
    Tor is free software and an open network that helps you defend against traffic analysis
builddeps  :
    - pkgconfig(libevent)
    - pkgconfig(libseccomp)
    - pkgconfig(libzstd)
    - asciidoc
    - ca-certs
setup      : |
    %configure_no_runstatedir
build      : |
    %make
install    : |
    %make_install
    rm $installdir/etc/tor/torrc.sample
    install -Dm00644 $pkgfiles/torrc $installdir/etc/tor/torrc
    install -Dm00644 $pkgfiles/tor.service $installdir/%libdir%/systemd/system/tor.service
    install -Dm00644 $pkgfiles/tor.sysusers $installdir/%libdir%/sysusers.d/tor.conf
    install -Dm00644 $pkgfiles/tor.tmpfiles $installdir/%libdir%/tmpfiles.d/tor.conf
    %install_license LICENSE
