# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : ansible
version    : 2.20.4
release    : 69
source     :
    - https://github.com/ansible/ansible/archive/refs/tags/v2.20.4.tar.gz : 253c90c6cacf95b3ee04ca8401805170562e2b72294454ccb97468a205990781
license    : GPL-3.0-or-later
homepage   : https://www.ansible.com/
component  : system.utils
summary    : Ansible is a radically simple IT automation system
description: |
    Ansible is a radically simple IT automation system
builddeps  :
    - pkgconfig(python3)
    - asciidoc
    - python-build
    - python-docutils
    - python-installer
    - python-jinja
    - python-setuptools
    - python-wheel
rundeps    :
    - python-jinja
    - python-jmespath
    - python-paramiko
    - python-resolvelib
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
    %install_license COPYING
