# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : check
version    : 0.15.2
release    : 12
source     :
    - https://github.com/libcheck/check/releases/download/0.15.2/check-0.15.2.tar.gz : a8de4e0bacfb4d76dd1c618ded263523b53b85d92a146d8835eb1a52932fa20a
homepage   : https://libcheck.github.io/check/
license    : LGPL-2.1
component  : programming.library
summary    : C unit testing framework
description: |
    Check is a unit testing framework for C. It features a simple interface for defining unit tests, putting little in the way of the developer. Tests are run in a separate address space, so both assertion failures and code errors that cause segmentation faults or other signals can be caught. Test results are reportable in the following: Subunit, TAP, XML, and a generic logging format.
setup      : |
    # Fix usage with musl
    export CFLAGS="${CFLAGS/-D_FORTIFY_SOURCE=2/}"
    %configure_no_runstatedir
build      : |
    %make
install    : |
    %make_install
    install -D -d -m 00755 $installdir/usr/include/musl
    for i in $installdir/usr/include/check*.h ; do
        ln -sv ../$(basename $i) $installdir/usr/include/musl/.
    done
    rm $installdir/usr/lib64/libcheck.a
check      : |
    %make check
