# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gnome-sudoku
version    : '50.1'
release    : 31
source     :
    - https://download.gnome.org/sources/gnome-sudoku/50/gnome-sudoku-50.1.tar.xz : 0b06c9777ecdb35a0fcd92d1649642549de816629f489f5d933315a34dcc7be2
homepage   : https://gitlab.gnome.org/GNOME/gnome-sudoku/-/wikis/home
license    : GPL-3.0-or-later
component  : games.puzzle
summary    : Sudoku - The popular Japanese logic puzzle
description: |
    Sudoku is a Japanese logic game that exploded in popularity in 2005. This is a logic-based number-placement puzzle in which a 9×9 square must be filled with the correct digits.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk4)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libadwaita-1)
    - pkgconfig(qqwing)
    - blueprint-compiler
    - desktop-file-utils
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
