# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : hunspell-da
version    : 2.9.086
release    : 6
source     :
    - https://stavekontrolden.dk/dictionaries/da_DK/da_DK-2.9.086.oxt : 19cd158a1c163183a96681b6ba11f7d0e7b5da8940e792e9e6ad30336bd21421
homepage   : https://www.stavekontrolden.dk/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MPL-1.1
component  : office.spelling
extract    : false
summary    : Danish hunspell dictionary
description: |
    Danish dictionary from Stavekontrolden / Danske ordbog til stavekontrol fra Stavekontrolden.
setup      : |
    unzip $sources/da_DK-$version.oxt
install    : |
    install -Dm00644 da_DK.{aff,dic} -t $installdir/usr/share/hunspell
