# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libavif
version    : 1.4.1
release    : 23
source     :
    - https://github.com/AOMediaCodec/libavif/archive/refs/tags/v1.4.1.tar.gz : d4aea31a4becb3273ba7968221be2e48148ba05eb8a68d14e671963e17785648
license    : BSD-2-Clause
component  : multimedia.library
homepage   : https://github.com/AOMediaCodec/libavif
summary    :
    - Library for encoding and decoding .avif files
    - tools : CLI tools for avif encoding/decoding
description: |
    libavif aims to be a friendly and portable C implementation of the AV1 Image File Format, capable of both encoding and decoding.
networking : true # needed to download libargparse for tests
builddeps  :
    - pkgconfig(SvtAv1Enc)
    - pkgconfig(aom)
    - pkgconfig(dav1d)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libjpeg)
    - pkgconfig(libpng)
    - pkgconfig(libsharpyuv)
    - pkgconfig(rav1e)
    - git # needed to download libargparse for tests
    - libyuv-devel
    - pandoc
checkdeps  :
    - pkgconfig(gtest)
setup      : |
    %cmake_ninja \
                 -DAVIF_BUILD_APPS=ON \
                 -DAVIF_BUILD_MAN_PAGES=ON \
                 -DAVIF_BUILD_TESTS=ON \
                 -DAVIF_CODEC_AOM=SYSTEM \
                 -DAVIF_CODEC_DAV1D=SYSTEM \
                 -DAVIF_CODEC_RAV1E=SYSTEM \
                 -DAVIF_CODEC_SVT=SYSTEM \
                 -DAVIF_GTEST=SYSTEM \
                 -DAVIF_BUILD_GDK_PIXBUF=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
check      : |
    %ninja_check
patterns   :
    - tools :
        - /usr/bin
        - /usr/share/man
