name       : observice
version    : 0.7.2
release    : 6
source     :
    - https://hp250.fritz.box/git/Python/observice/archive/0.7.2.tar.gz : f4b9bcb78c1a806b8f6b4e592e1b3b6c3be60c76b785cc3b27c6ce689aa3ee78
homepage   : https://hp250.fritz.box/git/Python/observice
license    : GPL3
component  : system.utils
summary    : Observice indicator tray app for showing the activity status of multiple services.
description: |
    Observice indicator tray app for showing the activity status of multiple services. One use case is to show the status of backup services so that the user is aware of running backup jobs.
# networking: yes # required for check
rundeps    :
    - libayatana-appindicator
    - python3
    - python-gobject
builddeps  :
    - python-hatchling 
    - python-installer
    - uv
build      : |
    uv build --wheel --no-build-isolation --no-managed-python --no-cache --offline
install    : |
    %python3_install
    install -Dm00644 src/applications/observice_indicator.desktop $installdir/usr/share/applications/observice_indicator.desktop
    mkdir -p $installdir/usr/share/icons/hicolor/scalable/apps/
    install -Dm00644 src/observice/icons/observice*.svg $installdir/usr/share/icons/hicolor/scalable/apps/
    # Add icon for deskop launcher
    install -Dm00644 src/observice/icons/observice_active.svg $installdir/usr/share/icons/hicolor/scalable/apps/observice.svg

    echo "Upload package with:"
    PACKAGE_FILE=$package-$version-$release-1-x86_64.eopkg
    echo "curl --user <username> --upload-file $PACKAGE_FILE https://hp250.fritz.box/git/api/packages/Python/generic/$package/$version-$release-1/$PACKAGE_FILE"

# check: |
#   %python3_test python3 -m pytest
