name       : observice
version    : 0.7.4
release    : 7
source     :
    - https://hp250.fritz.box/git/Python/observice/archive/v0.7.4.tar.gz : 66c24ecd69060d5cbe4f9f977db2315c93646d956deff6124a9c542ca5c5642e
homepage   : https://hp250.fritz.box/git/Python/observice
license    : GPL3
component  : system.utils
summary    : Observice indicator tray app for showing the activity status of multiple services.
description: |
    Observice indicator tray app for showing the activity status of multiple services. One use case is to show the status of backup services so that the user is aware of running backup jobs.
rundeps    :
    - libayatana-appindicator
    - libnotify
    - python3
    - python-gobject
builddeps  :
    - python-build
    - python-hatchling 
    - python-installer
    # test dependencies
    - libayatana-appindicator
    - libnotify
    - python-gobject
    - python-mock
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 src/applications/observice_indicator.desktop $installdir/usr/share/applications/observice_indicator.desktop
    mkdir -p $installdir/usr/share/icons/hicolor/scalable/apps/
    install -Dm00644 src/observice/icons/observice*.svg $installdir/usr/share/icons/hicolor/scalable/apps/
    # Add icon for deskop launcher
    install -Dm00644 src/observice/icons/observice_active.svg $installdir/usr/share/icons/hicolor/scalable/apps/observice.svg

    echo "Upload package with:"
    PACKAGE_FILE=$package-$version-$release-1-x86_64.eopkg
    echo "curl --user <username> --upload-file $PACKAGE_FILE https://hp250.fritz.box/git/api/packages/Python/generic/$package/$version-$release-1/$PACKAGE_FILE"

check: |
    %python3_test python3 -m pytest
